import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { PRODUCT_BLUEPRINT, buildMarketPolicySourceAudit, projectProductBlueprint } from "../src/feed/product-blueprint.js";
import { MARKET_POLICY_SOURCE_SAMPLE } from "../src/feed/market-policy-source-sample.js";
import { loadRegistry } from "../src/feed/registry.js";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8");
const prose = (text) => text.replace(/^>\s?/gm, "").replace(/\s+/g, " ").trim();

test("product blueprint: stable IDs, routes and gates are unique and fail closed", () => {
  const b = PRODUCT_BLUEPRINT;
  assert.equal(b.schemaVersion, 66);
  assert.match(b.stableId, /^NOWHOT-SYSTEM-BLUEPRINT-\d+$/);
  assert.match(b.charterId, /^NOWHOT-PRODUCT-CHARTER-\d+$/);
  assert.match(b.selectionEditorialId, /^NOWHOT-SELECTION-EDITORIAL-\d+$/);
  assert.equal(b.status.implementationAllowed, false);
  assert.equal(b.status.deploymentAllowed, false);
  assert.equal(b.status.localExperimentAllowed, true);
  assert.equal(b.status.code, "local_user_test_entry_pass");
  assert.equal(b.status.purposeAlignment, "pass_with_limits");
  assert.equal(b.currentGate.id, "B5-LOCAL-USER-TEST-ENTRY-CLOSED");

  const principleIds = b.principles.map((x) => x.id);
  assert.equal(new Set(principleIds).size, principleIds.length, "principle IDs must be unique");
  const paths = b.routes.map((x) => x.path);
  assert.equal(new Set(paths).size, paths.length, "route blueprint must not duplicate paths");
  for (const p of ["/", "/live", "/story/:clusterId", "/briefing", "/briefing/YYYY-MM-DD", "/briefing/YYYY-MM-DD/:edition", "/report"]) {
    assert.ok(paths.includes(p), `missing blueprint route ${p}`);
  }

  assert.deepEqual(b.phases.map((x) => x.id), ["B0", "B1", "B1.5", "B2", "B3", "B4", "B5", "B6"]);
  assert.equal(b.phases.find((x) => x.id === "B2").state, "legacy_local_implementation_complete");
  assert.equal(b.phases.find((x) => x.id === "B5").state, "local_user_test_ready_with_limits");
  assert.equal(b.phases.at(-1).state, "blocked", "production transition must remain blocked");
  assert.ok(Object.isFrozen(b) && Object.isFrozen(b.principles), "admin projection must be immutable");
});

test("product blueprint: adversarial review receipt is honest, bounded and fail closed", () => {
  const b = PRODUCT_BLUEPRINT;
  const r = b.adversarialReview;
  assert.equal(r.stableId, b.adversarialReviewId);
  assert.equal(r.state, "hold");
  assert.equal(r.execution.independentSeats, 6);
  assert.equal(r.execution.preservedLenses, 7);
  assert.equal(r.execution.reusedFollowUpLenses, 1);
  assert.equal(r.execution.newSeatsAfterCostInstruction, 0);
  assert.equal(r.reviewers.filter((x) => x.independent).length, 6);
  assert.ok(r.reviewers.filter((x) => x.independent).every((x) => x.verdict === "HOLD"));
  assert.equal(r.reviewers.find((x) => x.id === "R7").score, null);
  assert.equal(r.score.mean, 26.8);
  assert.equal(r.score.kind, "diagnostic_not_kpi");
  assert.deepEqual(r.experiments.map((x) => x.id), ["E1", "E2", "E3"]);
  assert.ok(r.commonFindings.every((x) => /^AR-P0-0[1-4]$/.test(x.id)));
  assert.ok(b.requirements.some((x) => x.id === "NH10-ADVERSARIAL-CLOSURE" && x.state === "hold"));
  assert.equal(b.nextPhase.id, "B5-MULTIDAY-CLOSED-USER-PILOT");
  assert.deepEqual(b.userTestEntryGates.map((x) => x.id), [
    "NH70-REVIEW-PACKET-PERSISTENCE",
    "NH71-INDEPENDENT-EDITORIAL-REVIEW",
    "NH72-DEFAULT-SUPPLY-RECOVERY",
    "NH73-DEFAULT-TODAY-SERVEABLE",
    "NH74-CATEGORY-COMBINATION-SERVEABILITY",
    "NH75-ADDITIVE-CATEGORY-UNION"
  ]);
  const persistenceGate = b.userTestEntryGates[0];
  assert.equal(persistenceGate.state, "local_runtime_pass");
  assert.equal(persistenceGate.receipt.packetId, "BRP-07rqta4");
  assert.equal(persistenceGate.receipt.issueCount, 42);
  assert.equal(persistenceGate.receipt.persisted, true);
  assert.equal(persistenceGate.receipt.canonicalEditionMutated, false);
  assert.equal(persistenceGate.receipt.externalLlmCalls, 0);
  assert.match(persistenceGate.receipt.rowFingerprintSha256, /^[a-f0-9]{64}$/);
  assert.match(persistenceGate.receipt.restartEnvelopeFingerprintSha256, /^[a-f0-9]{64}$/);
  const editorialReviewGate = b.userTestEntryGates[1];
  assert.equal(editorialReviewGate.state, "local_review_complete_with_holds");
  assert.equal(editorialReviewGate.receipt.reviewerType, "independent_ai");
  assert.equal(editorialReviewGate.receipt.humanIdentityVerified, false);
  assert.equal(editorialReviewGate.receipt.totalJudgments, 84);
  assert.equal(editorialReviewGate.receipt.adjudicatedFields, 16);
  assert.equal(editorialReviewGate.receipt.historicalHeldRows, 38);
  const supplyGate = b.userTestEntryGates[2];
  assert.equal(supplyGate.state, "local_runtime_pass");
  assert.equal(supplyGate.receipt.defaultCategoriesMet, 4);
  assert.equal(supplyGate.receipt.allCategoriesMet, 14);
  assert.equal(supplyGate.receipt.inventoryVersion, 21);
  const servingGate = b.userTestEntryGates[3];
  assert.equal(servingGate.state, "local_runtime_pass");
  assert.equal(servingGate.receipt.httpStatus, 200);
  assert.equal(servingGate.receipt.restartIdentityMatched, true);
  assert.equal(servingGate.receipt.mobileDocumentOverflow, false);
  assert.equal(servingGate.receipt.fullRegression, "1138/1138 PASS");
  const combinationGate = b.userTestEntryGates[4];
  assert.equal(combinationGate.state, "local_runtime_pass");
  assert.equal(combinationGate.receipt.readerCopyContractVersion, 11);
  assert.equal(combinationGate.receipt.liveRuntimeSampleCount, 139);
  assert.equal(combinationGate.receipt.liveRuntimeFailures, 0);
  assert.equal(combinationGate.receipt.fullRegression, "1139/1139 PASS");
  const additiveUnionGate = b.userTestEntryGates[5];
  assert.equal(additiveUnionGate.state, "local_runtime_pass");
  assert.equal(additiveUnionGate.receipt.currentObserved.businessAndScience, 28);
  assert.equal(additiveUnionGate.receipt.currentObserved.businessInPair, 14);
  assert.equal(additiveUnionGate.receipt.currentObserved.scienceInPair, 14);
  assert.equal(additiveUnionGate.receipt.currentObserved.uniqueClusterIdsInPair, 28);
  assert.equal(additiveUnionGate.receipt.currentObserved.categorySwitchesInPair, 27);
  assert.equal(additiveUnionGate.receipt.rules.qualityPadding, false);
  assert.equal(additiveUnionGate.receipt.rules.crossUrlTitleVariantDeduplication, "high_confidence_identity_only");
  assert.equal(additiveUnionGate.receipt.rules.distinctKeyNumbersPreserved, true);
  assert.equal(additiveUnionGate.receipt.contracts.fulfillmentVersion, 8);
  assert.equal(additiveUnionGate.receipt.contracts.editionChangeVersion, 9);
  assert.equal(additiveUnionGate.receipt.contracts.inventorySnapshotVersion, "v30");
  assert.equal(additiveUnionGate.receipt.mobile.documentOverflowX, false);
  assert.equal(additiveUnionGate.receipt.targetedRegression, "69/69 PASS");
  assert.equal(additiveUnionGate.receipt.fullRegression, "1145/1145 PASS");
  assert.equal(additiveUnionGate.receipt.independentAdversarialReview.verdict, "PASS");
  assert.deepEqual(additiveUnionGate.receipt.independentAdversarialReview.findings, { p0: 0, p1: 0, p2: 0 });
  assert.equal(additiveUnionGate.receipt.independentAdversarialReview.humanReview, false);
});

test("product blueprint: market-policy is the first category pack, not the product identity", () => {
  const b = PRODUCT_BLUEPRINT;
  const h = b.adversarialReview.beachhead;
  assert.equal(h.stableId, b.marketPolicyBeachheadId);
  assert.equal(h.role, "first_category_evidence_pack");
  assert.match(h.scopeNotice, /제품 전체 정체성이나 홈 기본값이 아니다/);
  assert.match(h.coreBoundary, /범용 콘텐츠 계약에는 강제하지 않는다/);
  assert.equal(h.audience, "국내외 주식 투자자");
  assert.equal(h.category, "시장·정책");
  assert.deepEqual(h.desks.map((x) => x.id), ["macro", "policy", "company", "market"]);
  for (const channel of ["금리·채권", "환율", "세금·규제", "무역·공급망", "실적·밸류에이션"]) {
    assert.ok(h.impactChannels.includes(channel), `missing market impact channel: ${channel}`);
  }
  assert.match(h.eligibility.politicalRule, /정치 일반은 제외/);
  assert.match(h.eligibility.politicalRule, /시장 영향 경로/);
  assert.ok(h.exclude.some((x) => /정당 공방/.test(x)));
  assert.ok(h.exclude.some((x) => /매수매도 추천/.test(x)));
  assert.match(b.adversarialReview.experiments.find((x) => x.id === "E1").detail, /목표 정밀도·검수 예산/);
  assert.doesNotMatch(b.adversarialReview.experiments.find((x) => x.id === "E1").detail, /100건/);
  assert.doesNotMatch(b.adversarialReview.experiments.find((x) => x.id === "E1").detail, /테크 기사/);
  assert.ok(b.requirements.some((x) => x.id === "NH11-MARKET-POLICY-BEACHHEAD"));
});

test("product blueprint: category architecture keeps the core extensible and category neutral", () => {
  const b = PRODUCT_BLUEPRINT;
  const c = b.categoryArchitecture;
  assert.equal(c.stableId, b.categoryArchitectureId);
  assert.equal(c.type, "extensible_category_platform");
  assert.deepEqual(c.layers.map((x) => x.id), ["core", "policyPack", "personalEdition"]);
  assert.ok(c.packContract.includes("sourcePolicy"));
  assert.ok(c.packContract.includes("verificationTriggers"));
  assert.ok(c.examplePacks.length >= 8);
  assert.equal(c.examplePacks.filter((x) => x.state === "first_evidence_pack").length, 1);
  assert.ok(c.boundaries.some((x) => /제품 전체 정체성/.test(x)));
  assert.ok(b.requirements.some((x) => x.id === "NH13-CATEGORY-PLATFORM-BOUNDARY" && x.state === "complete"));

  const requiredFields = b.contentContract.filter((x) => x.required).map((x) => x.field);
  for (const marketOnlyField of ["impactChannel", "asset", "valuation", "marketReaction"]) {
    assert.ok(!requiredFields.includes(marketOnlyField), `market-only field leaked into core: ${marketOnlyField}`);
  }
});

test("product blueprint: E1-0 source audit is derived from the live registry and fails closed", () => {
  const registry = loadRegistry();
  const audit = buildMarketPolicySourceAudit(registry);
  const enabled = registry.filter((x) => x.enabled);
  assert.equal(audit.current.byCategory.business, enabled.filter((x) => x.category === "business").length);
  assert.equal(audit.current.byCategory.news, enabled.filter((x) => x.category === "news").length);
  assert.equal(audit.current.byCategory.politics, enabled.filter((x) => x.category === "politics").length);
  assert.equal(audit.current.relevantSourceCount, Object.values(audit.current.byCategory).reduce((a, b) => a + b, 0));
  assert.equal(audit.current.primarySourceCount, 0);
  assert.ok(audit.current.byCategory.politics >= 3);
  assert.equal(audit.state, "hold");
  assert.equal(audit.candidates.length, 8);
  assert.ok(audit.candidates.some((x) => x.id === "KR-COMPANY-DART" && x.verification === "공식 문서 확인"));
  assert.ok(audit.candidates.some((x) => x.id === "US-POLICY-FED" && x.credential === "없음"));
  assert.ok(audit.candidates.every((x) => x.officialUrl.startsWith("https://")));
  assert.ok(audit.candidates.every((x) => !x.registered && !x.enabled));
  assert.deepEqual(audit.nextQueue.map((x) => x.order), [1, 2, 3]);
  assert.deepEqual(audit.nextQueue.map((x) => x.state), ["complete", "complete_with_limits", "complete_with_limits"]);
  const projection = projectProductBlueprint(registry);
  assert.equal(projection.adversarialReview.beachhead.sourceAudit.stableId, PRODUCT_BLUEPRINT.marketPolicySourceAuditId);
  assert.equal(projection.adversarialReview.beachhead.sourceSample.stableId, PRODUCT_BLUEPRINT.marketPolicySourceSampleId);
  assert.equal(projection.status.implementationAllowed, false);
  assert.ok(PRODUCT_BLUEPRINT.requirements.some((x) => x.id === "NH12-MARKET-POLICY-SOURCE-AUDIT" && x.state === "hold"));
});

test("product blueprint: E1-0B source sample is balanced, reproducible and honest about limits", () => {
  const sample = MARKET_POLICY_SOURCE_SAMPLE;
  assert.equal(sample.stableId, PRODUCT_BLUEPRINT.marketPolicySourceSampleId);
  assert.equal(sample.state, "complete_with_limits");
  assert.equal(sample.scope, "first_category_evidence_pack_only");
  assert.match(sample.scopeNotice, /전체 카테고리 품질/);
  assert.equal(sample.reports.length, 20);
  assert.equal(new Set(sample.reports.map((x) => x.id)).size, 20);
  assert.equal(new Set(sample.reports.map((x) => new URL(x.url).href)).size, 20);
  assert.deepEqual(sample.metrics.deskCounts, { macro: 5, policy: 5, company: 5, market: 5 });
  assert.equal(sample.metrics.sourceFamilyCount, 7);
  assert.ok(sample.reports.every((x) => x.sourceRole === "reported_secondary"));
  assert.ok(sample.reports.every((x) => x.syndicationStatus === "unknown"));
  assert.ok(sample.reports.every((x) => x.url.startsWith("https://")));
  assert.equal(sample.reports.find((x) => x.id === "MP-R15").poolMatchCount, 2);
  assert.equal(sample.metrics.selectedDuplicateUrlRows, 1);

  assert.equal(sample.officialChecks.length, 5);
  assert.equal(sample.metrics.matchedCheckCount, 3);
  assert.equal(sample.metrics.partialCheckCount, 2);
  const reportIds = new Set(sample.reports.map((x) => x.id));
  assert.ok(sample.officialChecks.every((x) => reportIds.has(x.reportId)));
  assert.ok(sample.officialChecks.flatMap((x) => x.urls).every((url) => url.startsWith("https://")));
  assert.equal(sample.method.dedupeRule, "normalized_url");
  assert.equal(sample.method.newKeys, 0);
  assert.equal(sample.method.newCollectors, 0);
  assert.equal(sample.method.llmCalls, 0);
  assert.deepEqual(sample.poolSnapshot, {
    sha256: "269523e7cf8954e32dbbf81015e521f4651ce772035c5efa06ba5c1051d55369",
    rowCount: 5290,
    uniqueUrlCount: 3278,
    duplicateRows: 2012,
    sourceCount: 76
  });
  assert.ok(Object.isFrozen(sample) && Object.isFrozen(sample.reports));
  assert.ok(PRODUCT_BLUEPRINT.requirements.some((x) => x.id === "NH14-MARKET-POLICY-SOURCE-SAMPLE" && x.state === "complete_with_limits"));
});

test("product blueprint: every required content field and development requirement has a stable identity", () => {
  const b = PRODUCT_BLUEPRINT;
  const required = b.contentContract.filter((x) => x.required).map((x) => x.field);
  for (const field of [
    "clusterId", "categoryIds", "editionIds", "headline", "whatHappened",
    "whyImportant", "whyHot", "changedSincePrevious",
    "scorecard", "metrics", "sourceEvidence", "confidence"
  ]) {
    assert.ok(required.includes(field), `required content field missing: ${field}`);
  }
  assert.equal(b.contentContract.find((x) => x.field === "whyForYou").required, false);
  assert.match(b.contentContract.find((x) => x.field === "whyForYou").role, /독자 화면에서는 숨김/);
  assert.ok(b.requirements.every((x) => /^NH\d{2}-[A-Z-]+$/.test(x.id)), "development requirements need stable IDs");
  assert.equal(new Set(b.requirements.map((x) => x.id)).size, b.requirements.length);
  assert.ok(b.notNow.some((x) => /운영 main/.test(x)));
  assert.ok(b.notNow.some((x) => /직접 수정/.test(x)));
});

test("product blueprint: local editorial candidate enhances the existing product and stays deployment-blocked", () => {
  const b = PRODUCT_BLUEPRINT;
  assert.equal(b.editionCandidateContract.stableId, b.editionCandidateContractId);
  assert.equal(b.localEditorialEdition.stableId, b.localEditorialEditionId);
  assert.equal(b.localEditorialEdition.scope, "existing_nowhot_editorial_enhancement");
  assert.ok(b.localEditorialEdition.reuses.includes("FeedEngine.briefing"));
  assert.equal(b.localEditorialEdition.llmCalls, 0);
  assert.equal(b.localEditorialEdition.llmCallsPerNewEvidenceEditionWhenEnabledMax, 2);
  assert.equal(b.localEditorialEdition.llmFeatureFlag, "NOWHOT_LOCAL_EDITORIAL_LLM=1");
  assert.equal(b.localEditorialEdition.featureFlag, "NOWHOT_LOCAL_EDITORIAL=1");
  assert.equal(b.localEditorialEdition.qaReceipt.stableId, "NOWHOT-LOCAL-QA-20260810-001");
  assert.deepEqual(b.localEditorialEdition.qaReceipt.tests, { total: 997, passed: 997, failed: 0 });
  assert.equal(b.localEditorialEdition.qaReceipt.visual.todayLiveRoundTrip, true);
  assert.equal(b.localEditorialEdition.editorialQualityReceipt.stableId, "NOWHOT-EDITORIAL-QA-20260810-001");
  assert.deepEqual(b.localEditorialEdition.editorialQualityReceipt.tests, { total: 1001, passed: 1001, failed: 0 });
  assert.equal(b.localEditorialEdition.editorialQualityReceipt.runtime.falseCrossSourceClaims, 0);
  assert.equal(b.localEditorialEdition.editorialQualityReceipt.blindReview.humanCompleted, 0);
  assert.equal(b.editionCandidateContract.version, 8);
  assert.equal(b.editionCandidateContract.carryoverMaxHours, 24);
  assert.equal(b.editionCandidateContract.carryoverCandidateFloor, 14);
  assert.deepEqual(b.editionCandidateContract.carryoverSourceRoles,
    ["primary", "reported_secondary", "community_signal", "first_party", "unknown"]);
  assert.equal(b.editorialQualityContract.stableId, b.editorialQualityContractId);
  assert.equal(b.editionChangeContract.stableId, b.editionChangeContractId);
  assert.equal(b.editionChangeContract.repeatRule.note.includes("최근 브리핑에서 다룬 사건"), true);
  assert.equal(b.localEditorialEdition.adds.includes("최근 세 판 사건 연속성"), true);
  assert.equal(b.editorialQualityContract.evaluationBoundary.e1State, "not_frozen");
  assert.equal(b.editorialQualityContract.evaluationBoundary.e1TargetSize, null);
  assert.equal(b.blindReviewPacketId, "NOWHOT-BLIND-REVIEW-PACKET-001");
  assert.equal(b.humanReviewQueueContractId, "NOWHOT-HUMAN-REVIEW-QUEUE-001");
  assert.equal(b.humanReviewQueueContract.activation, "explicit_after_first_packet");
  assert.ok(!("inputLimit" in b.editionCandidateContract));
  assert.match(b.adversarialReview.hardFacts.join(" "), /사전 고정 건수가 아니라 층화·정밀도·검수 예산/);
  assert.ok(b.requirements.some((x) => x.id === "NH15-EDITION-CANDIDATE-CONTRACT"));
  assert.ok(b.requirements.some((x) => x.id === "NH16-LOCAL-EDITORIAL-EDITION"));
  assert.ok(b.requirements.some((x) => x.id === "NH17-EDITORIAL-QUALITY-GATE"));
  assert.ok(b.requirements.some((x) => x.id === "NH18-BLIND-REVIEW-PACKET"));
  assert.ok(b.requirements.some((x) => x.id === "NH19-EDITION-CHANGE-CONTRACT"));
  assert.ok(b.requirements.some((x) => x.id === "NH20-HUMAN-REVIEW-LEDGER"));
  assert.ok(b.requirements.some((x) => x.id === "NH21-SLOT-AS-OF"));
  assert.ok(b.requirements.some((x) => x.id === "NH22-EDITORIAL-INVENTORY"));
  assert.ok(b.requirements.some((x) => x.id === "NH23-ELAPSED-SLOT-LEDGER"));
  assert.ok(b.requirements.some((x) => x.id === "NH24-HUMAN-REVIEW-ADJUDICATION"));
  assert.ok(b.requirements.some((x) => x.id === "NH25-EDITORIAL-LINEAGE"));
  assert.ok(b.requirements.some((x) => x.id === "NH26-EDITORIAL-LLM-RUNTIME"));
  assert.ok(b.requirements.some((x) => x.id === "NH27-PERSONALIZATION-INTEGRITY"));
  assert.ok(b.requirements.some((x) => x.id === "NH28-DYNAMIC-EDITION-DENSITY"));
  assert.ok(b.requirements.some((x) => x.id === "NH29-LATE-BACKFILL-ASOF"));
  assert.ok(b.requirements.some((x) => x.id === "NH30-HISTORICAL-CATEGORY-PARITY"));
  assert.ok(b.requirements.some((x) => x.id === "NH31-SEGMENT-ELAPSED-EVIDENCE"));
  assert.ok(b.requirements.some((x) => x.id === "NH32-INDEPENDENT-CORROBORATION"));
  assert.ok(b.requirements.some((x) => x.id === "NH34-EVIDENCE-WORDING-BOUNDARY"));
  assert.ok(b.requirements.some((x) => x.id === "NH35-CANDIDATE-QUALITY-FUNNEL"));
  assert.ok(b.requirements.some((x) => x.id === "NH36-QUALIFIED-SOURCE-REPAIR"));
  assert.ok(b.requirements.some((x) => x.id === "NH37-SLOT-SCHEDULER-OBSERVABILITY"));
  assert.ok(b.requirements.some((x) => x.id === "NH38-IMMUTABLE-HUMAN-REVIEW"));
  assert.ok(b.requirements.some((x) => x.id === "NH51-RESPONSE-ONLY-PERSONALIZATION"));
  assert.ok(b.requirements.some((x) => x.id === "NH52-EDITORIAL-CONTINUITY-READER-COPY"));
  assert.ok(b.requirements.some((x) => x.id === "NH53-UNIFIED-VIEW-SWITCH"));
  assert.ok(b.requirements.some((x) => x.id === "NH54-EDITORIAL-REVIEW-DESK"));
  assert.ok(b.requirements.some((x) => x.id === "NH55-READER-QUALITY-FEEDBACK"));
  assert.ok(b.requirements.some((x) => x.id === "NH56-UNSERVED-QUALITY-CARRYOVER"));
  assert.ok(b.requirements.some((x) => x.id === "NH57-PURPOSE-ALIGNMENT-ADVERSARIAL-REVIEW" && x.state === "hold"));
  const feedbackReceipt = b.localEditorialEdition.readerQualityFeedbackQaReceipt;
  assert.equal(feedbackReceipt.rules.recentEditionHistoryDepth, 3);
  assert.equal(feedbackReceipt.rules.immutableSavedEditions, true);
  assert.equal(feedbackReceipt.projectedEvening.selectedIssues, 42);
  assert.equal(feedbackReceipt.projectedEvening.machineHoldClusters, 24);
  assert.equal(feedbackReceipt.projectedEvening.nearDuplicateHolds, 36);
  assert.equal(feedbackReceipt.projectedEvening.targetDefectsRemaining, 0);
  assert.deepEqual(feedbackReceipt.projectedEvening.underfilledCategoryIds, ["science"]);
  assert.match(feedbackReceipt.boundary, /실제 19시/);
  assert.equal(b.editorialSchedulerStatusId, "NOWHOT-EDITORIAL-SCHEDULER-STATUS-001");
  assert.equal(b.editorialSourceIdentityContract.stableId, b.editorialSourceIdentityContractId);
  assert.equal(b.editorialFulfillmentContract.version, 8);
  assert.equal(b.editorialFulfillmentContract.uniqueIssueRule.maxSelectedCategoryCreditsPerIssue, 14);
  assert.equal(b.editorialFulfillmentContract.issueBudget.perSelectedCategory, 14);
  assert.equal(b.editorialFulfillmentContract.issueBudget.maxPublished, 196);
  assert.match(b.editorialFulfillmentContract.categoryUnionRule, /중요도 순위 층/);
  assert.equal(b.localEditorialEdition.editionChangeReceipt.humanReview.completedRows, 0);
  assert.equal(b.localEditorialEdition.editionChangeReceipt.humanReview.qualityPass, false);
  assert.equal(b.localEditorialEdition.editionChangeReceipt.humanReview.identityProof, false);
  assert.deepEqual(b.localEditorialEdition.editionChangeReceipt.tests, { total: 1006, passed: 1006, failed: 0 });
  assert.equal(b.localEditorialEdition.editionChangeReceipt.replay.actualElapsedTime, false);
  assert.equal(b.localEditorialEdition.editorialInventoryReceipt.contractId, b.editorialInventoryContractId);
  assert.equal(b.localEditorialEdition.editorialInventoryReceipt.snapshotVersion, "v30");
  assert.equal(b.localEditorialEdition.editorialInventoryReceipt.compatibility.pass, true);
  assert.equal(b.localEditorialEdition.editorialInventoryReceipt.llmCalls, 0);
  assert.deepEqual(b.localEditorialEdition.editorialInventoryReceipt.tests.fullRegression, { total: 1052, passed: 1052, failed: 0 });
  assert.equal(b.localEditorialEdition.elapsedEvidenceReceipt.contractId, b.elapsedEditionEvidenceContractId);
  assert.equal(b.localEditorialEdition.elapsedEvidenceReceipt.captureWindowMs, 10 * 60 * 1000);
  assert.match(b.localEditorialEdition.elapsedEvidenceReceipt.segmentProofRule, /같은 공유 카테고리 조합/);
  assert.equal(b.localEditorialEdition.elapsedEvidenceReceipt.actualMorningObservation.captureMode, "scheduled_window");
  assert.equal(b.localEditorialEdition.elapsedEvidenceReceipt.actualMorningObservation.capturedCount, 1);
  assert.equal(b.localEditorialEdition.elapsedEvidenceReceipt.actualMorningObservation.actualElapsedTimeProof, false);
  assert.deepEqual(b.localEditorialEdition.elapsedEvidenceReceipt.tests.fullRegression, { total: 1052, passed: 1052, failed: 0 });
  assert.deepEqual(b.localEditorialEdition.editorialLineageReceipt.tests.fullRegression, { total: 1052, passed: 1052, failed: 0 });
  assert.equal(b.localEditorialEdition.editorialLineageReceipt.observedLlmCalls, 0);
  assert.equal(b.localEditorialEdition.editorialLineageReceipt.state, "local_path_verified_model_unobserved");
  assert.equal(b.localEditorialEdition.editorialLineageReceipt.canary.contractId, b.editorialLlmCanaryContractId);
  assert.equal(b.localEditorialEdition.editorialLineageReceipt.canary.requestedIssueCount, 3);
  assert.equal(b.localEditorialEdition.editorialLineageReceipt.canary.maxCalls, 2);
  assert.equal(b.localEditorialEdition.editorialLineageReceipt.canary.externalCalls, 0);
  assert.equal(b.localEditorialEdition.editorialLineageReceipt.canary.keyAvailable, false);
  assert.equal(b.editorialFulfillmentContract.noFixedItemCount, true);
  assert.equal(b.editorialPersonalizationContract.stableId, b.editorialPersonalizationContractId);
  assert.equal(b.editorialReaderCopyContract.stableId, b.editorialReaderCopyContractId);
  assert.equal(b.localEditorialEdition.personalizationIntegrityReceipt.contractId, b.editorialFulfillmentContractId);
  assert.deepEqual(
    b.localEditorialEdition.personalizationIntegrityReceipt.tests.focusedRegression,
    { total: 88, passed: 88, failed: 0 }
  );
  assert.deepEqual(
    b.localEditorialEdition.personalizationIntegrityReceipt.tests.fullRegression,
    { total: 1052, passed: 1052, failed: 0 }
  );
  const projectionReceipt = b.localEditorialEdition.personalizationProjectionQaReceipt;
  assert.equal(projectionReceipt.contractId, b.editorialPersonalizationContractId);
  assert.equal(projectionReceipt.rules.sharedCanonicalIsUserNeutral, true);
  assert.equal(projectionReceipt.rules.requestUserTopicCannotEnterSharedEdition, true);
  assert.equal(projectionReceipt.rules.selectedCategoriesOnly, true);
  assert.equal(projectionReceipt.rules.responseOrderOnly, true);
  assert.equal(projectionReceipt.rules.issueCountUnchanged, true);
  assert.equal(projectionReceipt.rules.noPerUserEditionPersistence, true);
  assert.equal(projectionReceipt.rules.llmCalls, 0);
  assert.equal(projectionReceipt.rules.fixedProductItemCount, false);
  assert.deepEqual(projectionReceipt.tests.focusedRegression, { total: 20, passed: 20, failed: 0 });
  assert.deepEqual(projectionReceipt.tests.fullRegression, { total: 1081, passed: 1081, failed: 0 });
  const continuityReceipt = b.localEditorialEdition.continuityReaderShellQaReceipt;
  assert.equal(continuityReceipt.contractIds.editionChange, b.editionChangeContractId);
  assert.equal(continuityReceipt.contractIds.readerCopy, b.editorialReaderCopyContractId);
  assert.equal(continuityReceipt.rules.responseOnlyContinuityProjection, true);
  assert.equal(continuityReceipt.rules.canonicalSnapshotMutated, false);
  assert.equal(continuityReceipt.rules.whyForYouHiddenFromReader, true);
  assert.equal(continuityReceipt.rules.unifiedTodayLiveSwitch, true);
  assert.equal(continuityReceipt.rules.indicatorMotionMs, 210);
  assert.equal(continuityReceipt.actualStoredRegression.matchMethod, "shared_event_terms");
  assert.deepEqual(continuityReceipt.actualStoredRegression.matchedTerms, ["호르무즈", "협상", "난항", "국제유가"]);
  assert.deepEqual(continuityReceipt.tests.focusedRegression, { total: 19, passed: 19, failed: 0 });
  assert.deepEqual(continuityReceipt.tests.fullRegression, { total: 1087, passed: 1087, failed: 0 });
  assert.equal(continuityReceipt.visual.state, "local_browser_qa_pass");
  assert.equal(continuityReceipt.visual.brandIdentityVisible, true);
  assert.equal(continuityReceipt.visual.stableHeaderCoordinates, true);
  assert.deepEqual(continuityReceipt.visual.desktopTabX, { today: 364.5, live: 424.8359375 });
  assert.deepEqual(continuityReceipt.visual.mobileTabX, { today: 144, live: 196.3359375 });
  assert.equal(continuityReceipt.visual.headerOverlap, false);
  assert.equal(continuityReceipt.visual.horizontalOverflow, false);
  assert.equal(continuityReceipt.visual.pageErrors, 0);
  const reviewDeskReceipt = b.localEditorialEdition.editorialReviewDeskQaReceipt;
  assert.equal(b.editorialReviewDeskContract.stableId, b.editorialReviewDeskContractId);
  assert.equal(reviewDeskReceipt.contractId, b.editorialReviewDeskContractId);
  assert.equal(reviewDeskReceipt.route, "/admin/editorial-desk");
  assert.equal(reviewDeskReceipt.api, "/api/admin/editorial-desk");
  assert.equal(reviewDeskReceipt.rules.readerSurfaceIsPrimary, true);
  assert.equal(reviewDeskReceipt.rules.currentReviewerOnly, true);
  assert.equal(reviewDeskReceipt.rules.otherReviewerAnswersHiddenUntilComplete, true);
  assert.equal(reviewDeskReceipt.rules.machineGateHidden, true);
  assert.equal(reviewDeskReceipt.rules.whyForYouHidden, true);
  assert.equal(reviewDeskReceipt.rules.packetRowsMutated, false);
  assert.equal(reviewDeskReceipt.rules.llmCalls, 0);
  assert.equal(reviewDeskReceipt.actualLocalPacket.issueCount, 42);
  assert.equal(reviewDeskReceipt.actualLocalPacket.reviewerACompleted, 0);
  assert.equal(reviewDeskReceipt.actualLocalPacket.reviewerBCompleted, 0);
  assert.equal(reviewDeskReceipt.actualLocalPacket.identityProof, false);
  assert.deepEqual(reviewDeskReceipt.tests.focusedRegression, { total: 24, passed: 24, failed: 0 });
  assert.deepEqual(reviewDeskReceipt.tests.fullRegression, { total: 1090, passed: 1090, failed: 0 });
  assert.equal(reviewDeskReceipt.visual.state, "local_browser_qa_pass");
  assert.equal(reviewDeskReceipt.visual.mobileHorizontalIssueQueue, true);
  assert.equal(reviewDeskReceipt.visual.mobileRubricBelowStory, true);
  assert.equal(reviewDeskReceipt.visual.horizontalOverflow, false);
  assert.equal(reviewDeskReceipt.visual.pageErrors, 0);
  assert.equal(reviewDeskReceipt.visual.pageWarnings, 0);
  assert.equal(b.selectionEngine.clusterContract.version, 2);
  assert.match(b.selectionEngine.clusterContract.mergeRule, /완전일치/);
  assert.ok(b.selectionEngine.clusterContract.forbiddenMergeSignals.includes("출처 기본 태그"));
  assert.equal(b.localEditorialEdition.clusterQaReceipt.snapshotVersion, "v12");
  assert.equal(b.localEditorialEdition.clusterQaReceipt.fixture.removedFalseMergeCount, 2);
  assert.equal(b.localEditorialEdition.clusterQaReceipt.fixture.selectedMultiUrlIssueCount, 0);
  const supplyReceipt = b.localEditorialEdition.categorySupplyQaReceipt;
  assert.equal(supplyReceipt.snapshotVersion, "v13");
  assert.equal(supplyReceipt.gamingOnlyReplay.candidateCount, 25);
  assert.equal(supplyReceipt.gamingOnlyReplay.issueCount, 14);
  assert.equal(supplyReceipt.gamingOnlyReplay.generalNewsSourceSpread, 1);
  assert.equal(supplyReceipt.allCategoryReplay.fulfilledCategoryCount, 14);
  assert.deepEqual(supplyReceipt.allCategoryReplay.underfilledCategoryIds, []);
  assert.match(supplyReceipt.boundary, /실제 07시 정시 판/);
  const wordingReceipt = b.localEditorialEdition.evidenceWordingQaReceipt;
  assert.equal(wordingReceipt.rules.relatedCoverageIsNotDirectCorroboration, true);
  assert.equal(wordingReceipt.rules.particleSafeSentence, true);
  assert.equal(wordingReceipt.example.directlyObservedOriginals, 1);
  assert.match(wordingReceipt.example.allowed, /직접 확인한 원문은 한 건/);
  assert.deepEqual(wordingReceipt.tests.fullRegression, { total: 1053, passed: 1053, failed: 0 });
  assert.match(wordingReceipt.boundary, /기사 사실의 진실성/);
  const funnelReceipt = b.localEditorialEdition.candidateFunnelQaReceipt;
  assert.equal(funnelReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(funnelReceipt.rules.machineGateBeforeNearDuplicateDedupe, true);
  assert.deepEqual(funnelReceipt.rules.perCategoryFunnel, [
    "inputItemCount", "clusterCount", "machinePassClusterCount",
    "qualifiedClusterCount", "draftSelectedCount", "issueCount"
  ]);
  assert.equal(funnelReceipt.diagnosedActualMorning.immutableReceiptPreserved, true);
  assert.deepEqual(funnelReceipt.tests.fullRegression, { total: 1054, passed: 1054, failed: 0 });
  assert.equal(funnelReceipt.visual.documentHorizontalOverflow, false);
  assert.equal(funnelReceipt.visual.consoleErrors, 0);
  assert.match(funnelReceipt.boundary, /사람 품질 PASS/);
  const sourceRepairReceipt = b.localEditorialEdition.sourceRepairQaReceipt;
  assert.equal(sourceRepairReceipt.rules.fixedCandidateTarget, false);
  assert.equal(sourceRepairReceipt.rules.sourceInputsAreOwnContent, false);
  assert.equal(sourceRepairReceipt.rules.scienceVerifiedSourcePriority, true);
  assert.equal(sourceRepairReceipt.sources.length, 3);
  assert.equal(sourceRepairReceipt.replay.science.finalIssueCount, 7);
  assert.equal(sourceRepairReceipt.replay.science.verifiedSourceLeadCount, 6);
  assert.equal(sourceRepairReceipt.replay.fashion.finalIssueCount, 9);
  assert.equal(sourceRepairReceipt.replay.retiredBroadHypebeastIssueCount, 0);
  assert.deepEqual(sourceRepairReceipt.tests.fullRegression, { total: 1058, passed: 1058, failed: 0 });
  assert.match(sourceRepairReceipt.boundary, /자체 콘텐츠가 아니라 편집 원료/);
  assert.match(b.changeLog.find((x) => x.id === "DEVCHG-NOWHOT-20260810-010").title, /폐기된 초기안/);
  assert.ok(b.changeLog.some((x) => x.id === "DEVCHG-NOWHOT-20260811-029"));
  assert.equal(b.changeId, "DEVCHG-NOWHOT-20260813-070");
  const carryoverReceipt = b.localEditorialEdition.unservedQualityCarryoverQaReceipt;
  assert.equal(carryoverReceipt.rules.requiresPriorEdition, true);
  assert.equal(carryoverReceipt.rules.servedCanonicalUrlsExcluded, true);
  assert.equal(carryoverReceipt.rules.communitySignalsExcluded, true);
  assert.equal(carryoverReceipt.rules.currentSlotIssuesRankFirst, true);
  assert.equal(carryoverReceipt.rules.fixedCandidateTarget, false);
  assert.equal(carryoverReceipt.projectedRuntimeReplay.evening.finalScienceIssues, 2);
  assert.equal(carryoverReceipt.projectedRuntimeReplay.evening.finalScienceCarryoverIssues, 1);
  assert.equal(carryoverReceipt.projectedRuntimeReplay.evening.fulfillmentState, "fulfillment_complete");
  assert.deepEqual(carryoverReceipt.tests.focusedRegression, { total: 90, passed: 90, failed: 0 });
  assert.deepEqual(carryoverReceipt.tests.fullRegression, { total: 1094, passed: 1094, failed: 0 });
  assert.equal(carryoverReceipt.visual.desktop.identity, "지금핫 NowHot 맞춰가는 중");
  assert.equal(carryoverReceipt.visual.mobile.identity, "지금핫 맞춰가는 중");
  const alignmentReview = b.localEditorialEdition.purposeAlignmentAdversarialReviewReceipt;
  assert.equal(alignmentReview.stableId, b.purposeAlignmentReviewId);
  assert.equal(alignmentReview.state, "hold");
  assert.equal(alignmentReview.reviewers.length, 5);
  assert.ok(alignmentReview.reviewers.every((x) => x.verdict === "HOLD"));
  assert.equal(alignmentReview.score.mean, 47.4);
  assert.equal(alignmentReview.verifiedFacts.humanDoubleReviewedRows, "0/84");
  assert.equal(alignmentReview.verifiedFacts.projectedEveningReaderRowsFrozen, "0/42");
  assert.equal(alignmentReview.independence.actualNamedCompanyParticipation, false);
  assert.match(alignmentReview.boundary, /모의 직무 렌즈/);
  const readerFreezeReceipt = b.localEditorialEdition.readerPayloadFreezeQaReceipt;
  assert.equal(readerFreezeReceipt.stableId, "NOWHOT-READER-PAYLOAD-FREEZE-QA-001");
  assert.equal(readerFreezeReceipt.state, "reader_copy_hold");
  assert.equal(readerFreezeReceipt.contracts.packetVersion, 2);
  assert.equal(readerFreezeReceipt.contracts.readerContractVersion, 3);
  assert.equal(readerFreezeReceipt.actualRuntime.readerFrozen, "42/42");
  assert.equal(readerFreezeReceipt.actualRuntime.readerIssuePass, "41/42");
  assert.equal(readerFreezeReceipt.actualRuntime.readerPacketPass, false);
  assert.equal(readerFreezeReceipt.actualRuntime.humanState, "human_annotation_ready");
  assert.equal(readerFreezeReceipt.packetDiversity.whyImportant.pass, false);
  assert.equal(readerFreezeReceipt.packetDiversity.whyNow.pass, true);
  assert.equal(readerFreezeReceipt.packetDiversity.watchNext.pass, false);
  assert.deepEqual(readerFreezeReceipt.tests.fullRegression, { total: 1097, passed: 1097, failed: 0 });
  assert.match(readerFreezeReceipt.boundary, /reader_copy_hold/);
  assert.ok(b.requirements.some((x) => x.id === "NH58-READER-PAYLOAD-FREEZE-GATE" && x.state === "hold"));
  const eventFrameReceipt = b.localEditorialEdition.readerEventFrameQaReceipt;
  assert.equal(eventFrameReceipt.stableId, "NOWHOT-READER-EVENT-FRAME-QA-001");
  assert.equal(eventFrameReceipt.contracts.packetVersion, 3);
  assert.equal(eventFrameReceipt.contracts.readerContractVersion, 5);
  assert.equal(eventFrameReceipt.actualRuntime.readerIssuePass, "41/42");
  assert.equal(eventFrameReceipt.actualRuntime.readerPacketPass, true);
  assert.equal(eventFrameReceipt.editingRule.eventFrames, 21);
  assert.equal(eventFrameReceipt.packetDiversity.whyImportant.maxExactRepeat, 2);
  assert.equal(eventFrameReceipt.packetDiversity.watchNext.maxExactRepeat, 3);
  assert.equal(eventFrameReceipt.immutableUpgrade.regressionState, "pass");
  assert.equal(eventFrameReceipt.elapsedRuntime.capturedSlots, "3/3");
  assert.equal(eventFrameReceipt.elapsedRuntime.completeSegmentProofs, "1/5");
  assert.equal(eventFrameReceipt.elapsedRuntime.actualElapsedTimeProof, false);
  assert.deepEqual(eventFrameReceipt.tests.fullRegression, { total: 1103, passed: 1103, failed: 0 });
  assert.equal(eventFrameReceipt.adversarialReview.actualNamedCompanyParticipation, false);
  assert.equal(eventFrameReceipt.adversarialReview.reviewers.length, 5);
  assert.ok(eventFrameReceipt.adversarialReview.reviewers.every((x) => x.verdict === "HOLD"));
  assert.ok(b.requirements.some((x) => x.id === "NH59-READER-EVENT-FRAME-COPY" && x.state === "hold"));
  const independentAudit = b.localEditorialEdition.independentAdversarialAuditReceipt;
  assert.equal(independentAudit.stableId, b.independentAdversarialAuditId);
  assert.equal(independentAudit.state, "block");
  assert.deepEqual(independentAudit.score.verdicts, { block: 1, hold: 2, go: 0 });
  assert.equal(independentAudit.score.mean, 46);
  assert.equal(independentAudit.independence.actualHumanParticipation, false);
  assert.equal(independentAudit.independence.actualNamedCompanyParticipation, false);
  assert.equal(independentAudit.directReproductions.length, 2);
  assert.ok(independentAudit.directReproductions.every((x) => x.result === "confirmed"));
  assert.equal(independentAudit.regressionBoundary.newlyFoundCounterexamplesCovered, "0/4");
  assert.ok(b.requirements.some((x) => x.id === "NH60-INDEPENDENT-ADVERSARIAL-AUDIT" && x.state === "blocked"));
  const repair = b.localEditorialEdition.counterexampleRepairReceipt;
  assert.equal(repair.stableId, b.counterexampleRepairId);
  assert.equal(repair.state, "local_repair_pass_reaudit_pending");
  assert.equal(repair.repairs.length, 4);
  assert.ok(repair.repairs.every((x) => x.state === "regression_pass"));
  assert.equal(repair.contracts.lineageFingerprintVersion, 3);
  assert.equal(repair.contracts.llmVersion, 2);
  assert.equal(repair.contracts.readerCopyVersion, 6);
  assert.equal(repair.green.counterexamplesCovered, "4/4");
  assert.equal(repair.green.fullRegression, "1107/1107 PASS");
  assert.ok(b.requirements.some((x) => x.id === "NH61-COUNTEREXAMPLE-REPAIR" && x.state === "local_code_qa_pass_with_limits"));
  const reaudit = b.localEditorialEdition.independentReauditReceipt;
  assert.equal(reaudit.stableId, b.independentReauditId);
  assert.equal(reaudit.state, "block");
  assert.deepEqual(reaudit.score.verdicts, { block: 2, hold: 1, go: 0 });
  assert.equal(reaudit.score.mean, 46);
  assert.equal(reaudit.independence.completedFinalReviewers, 3);
  assert.equal(reaudit.independence.replacedErroredAttempt, 1);
  assert.equal(reaudit.independence.actualHumanParticipation, false);
  assert.equal(reaudit.independence.actualNamedCompanyParticipation, false);
  assert.equal(reaudit.independence.strictBlind, false);
  assert.equal(reaudit.actualRuntime.allCategoryEvening.servedDespiteReaderHold, true);
  assert.equal(reaudit.actualRuntime.allCategoryEvening.readerHoldRows, 5);
  assert.equal(reaudit.actualRuntime.responsePacketDrift.mismatchedRows, "42/42");
  assert.equal(reaudit.directReproductions.length, 7);
  assert.ok(reaudit.directReproductions.every((x) => x.result === "confirmed"));
  assert.equal(reaudit.previousRepairClosure.covered, "4/4");
  assert.equal(reaudit.nextRequired.id, "B6-SERVEABLE-EDITION-REPAIR");
  assert.equal(reaudit.recordingQa.fullRegression, "1107/1107 PASS");
  assert.ok(b.requirements.some((x) => x.id === "NH62-INDEPENDENT-REAUDIT" && x.state === "blocked"));
  const servingRepair = b.localEditorialEdition.serveableEditionRepairReceipt;
  assert.equal(servingRepair.stableId, b.serveableEditionRepairId);
  assert.equal(servingRepair.state, "local_repair_pass_with_limits");
  assert.equal(servingRepair.contract.stableId, b.editorialServingContractId);
  assert.equal(servingRepair.contract.version, b.editorialServingContract.version);
  assert.equal(servingRepair.contract.humanReviewRequired, false);
  assert.equal(servingRepair.red.http200, 42);
  assert.equal(servingRepair.repairs.length, 4);
  assert.ok(servingRepair.repairs.every((x) => x.state === "regression_pass"));
  assert.equal(servingRepair.green.routeCounterexamples, "4/4 PASS");
  assert.equal(servingRepair.green.fullRegression, "1114/1114 PASS");
  assert.equal(servingRepair.green.holdResponseStatus, 409);
  assert.equal(servingRepair.green.tamperedReceiptRejected, true);
  assert.equal(servingRepair.nextRequired.id, "B6-READER-LINEAGE-GROUNDING-REPAIR");
  assert.ok(b.requirements.some((x) => x.id === "NH63-SERVEABLE-EDITION-GATE" && x.state === "local_code_qa_pass_with_limits"));
  const readerLineageRepair = b.localEditorialEdition.readerLineageGroundingRepairReceipt;
  assert.equal(readerLineageRepair.stableId, b.readerLineageGroundingRepairId);
  assert.equal(readerLineageRepair.state, "local_repair_pass_with_limits");
  assert.equal(readerLineageRepair.contracts.lineageFingerprintVersion, 4);
  assert.equal(readerLineageRepair.contracts.readerVersion, 7);
  assert.equal(readerLineageRepair.contracts.packetVersion, 4);
  assert.equal(readerLineageRepair.contracts.visibleFields.length, 7);
  assert.equal(readerLineageRepair.red.focusedRegression, "11/14 PASS · 3 FAIL");
  assert.equal(readerLineageRepair.repairs.length, 4);
  assert.ok(readerLineageRepair.repairs.every((x) => x.state === "regression_pass"));
  assert.equal(readerLineageRepair.green.readerFieldTamperHeld, "7/7");
  assert.equal(readerLineageRepair.green.fullRegression, "1117/1117 PASS");
  assert.equal(readerLineageRepair.nextRequired.id, "B6-EVENT-CONTINUITY-FRAME-REPAIR");
  assert.ok(b.requirements.some((x) => x.id === "NH64-READER-LINEAGE-GROUNDING" && x.state === "local_code_qa_pass_with_limits"));
  const eventContinuityRepair = b.localEditorialEdition.eventContinuityFrameRepairReceipt;
  assert.equal(eventContinuityRepair.stableId, b.eventContinuityFrameRepairId);
  assert.equal(eventContinuityRepair.state, "local_repair_pass_with_limits");
  assert.equal(eventContinuityRepair.contracts.editionChangeVersion, 4);
  assert.equal(eventContinuityRepair.contracts.lineageVersion, 4);
  assert.equal(eventContinuityRepair.contracts.lineageFingerprintVersion, 5);
  assert.equal(eventContinuityRepair.contracts.readerVersion, 8);
  assert.equal(eventContinuityRepair.contracts.readerFingerprintVersion, 2);
  assert.equal(eventContinuityRepair.contracts.eventFrameVersion, 1);
  assert.equal(eventContinuityRepair.contracts.qualityVersion, 9);
  assert.equal(eventContinuityRepair.contracts.packetVersion, 5);
  assert.equal(eventContinuityRepair.red.focusedRegression, "22/25 PASS · 3 FAIL");
  assert.equal(eventContinuityRepair.repairs.length, 4);
  assert.ok(eventContinuityRepair.repairs.every((x) => x.state === "regression_pass"));
  assert.equal(eventContinuityRepair.green.coreRegression, "26/26 PASS");
  assert.equal(eventContinuityRepair.green.integrationRegression, "70/70 PASS");
  assert.equal(eventContinuityRepair.green.fullRegression, "1121/1121 PASS");
  assert.equal(eventContinuityRepair.green.sameHormuzEventContinues, true);
  assert.equal(eventContinuityRepair.green.distinctGalaxyEventsSeparated, true);
  assert.equal(eventContinuityRepair.green.relatedObservationExcludedFromIdentityAndFrame, true);
  assert.equal(eventContinuityRepair.green.primaryClaimEvidenceIsolated, true);
  assert.equal(eventContinuityRepair.green.externalLlmCalls, 0);
  assert.equal(eventContinuityRepair.nextRequired.id, "B6-CATEGORY-UNIQUE-FULFILLMENT-REPAIR");
  assert.ok(b.requirements.some((x) => x.id === "NH65-EVENT-CONTINUITY-FRAME-GROUNDING" && x.state === "local_code_qa_pass_with_limits"));
  const categoryUniqueRepair = b.localEditorialEdition.categoryUniqueFulfillmentRepairReceipt;
  assert.equal(categoryUniqueRepair.stableId, b.categoryUniqueFulfillmentRepairId);
  assert.equal(categoryUniqueRepair.state, "local_repair_pass_with_limits");
  assert.equal(categoryUniqueRepair.contracts.fulfillmentId, b.editorialFulfillmentContractId);
  assert.equal(categoryUniqueRepair.contracts.fulfillmentVersion, 4);
  assert.equal(categoryUniqueRepair.contracts.maxSelectedCategoryCreditsPerIssue, 1);
  assert.equal(categoryUniqueRepair.red.focusedRegression, "5/8 PASS · 3 FAIL");
  assert.equal(categoryUniqueRepair.repairs.length, 4);
  assert.ok(categoryUniqueRepair.repairs.every((x) => x.state === "regression_pass"));
  assert.equal(categoryUniqueRepair.green.coreRegression, "8/8 PASS");
  assert.equal(categoryUniqueRepair.green.servingRegression, "16/16 PASS");
  assert.equal(categoryUniqueRepair.green.editionIntegrationRegression, "22/22 PASS");
  assert.equal(categoryUniqueRepair.green.fullRegression, "1125/1125 PASS");
  assert.equal(categoryUniqueRepair.green.singleIssueMaximumCredits, 1);
  assert.equal(categoryUniqueRepair.green.underfilledResponseHeld, true);
  assert.equal(categoryUniqueRepair.green.externalLlmCalls, 0);
  assert.equal(categoryUniqueRepair.nextRequired.id, "B6-FEEDBACK-ROLLBACK-REPAIR");
  assert.ok(b.requirements.some((x) => x.id === "NH66-CATEGORY-UNIQUE-FULFILLMENT" && x.state === "local_code_qa_pass_with_limits"));
  const feedbackRollbackRepair = b.localEditorialEdition.feedbackRollbackRepairReceipt;
  assert.equal(feedbackRollbackRepair.stableId, b.feedbackRollbackRepairId);
  assert.equal(feedbackRollbackRepair.state, "local_repair_pass_with_limits");
  assert.equal(feedbackRollbackRepair.contract.stableId, b.feedbackOverlayContractId);
  assert.equal(feedbackRollbackRepair.contract.version, 1);
  assert.equal(feedbackRollbackRepair.contract.eventJournalEntriesPerUser, 0);
  assert.equal(feedbackRollbackRepair.red.focusedRegression, "0/1 PASS · 1 FAIL");
  assert.equal(feedbackRollbackRepair.repairs.length, 4);
  assert.ok(feedbackRollbackRepair.repairs.every((x) => x.state === "regression_pass"));
  assert.equal(feedbackRollbackRepair.green.focusedRegression, "4/4 PASS");
  assert.equal(feedbackRollbackRepair.green.feedRegression, "179/179 PASS");
  assert.equal(feedbackRollbackRepair.green.fullRegression, "1126/1126 PASS");
  assert.equal(feedbackRollbackRepair.green.restartStateMatchesControl, true);
  assert.equal(feedbackRollbackRepair.green.stagingUsersObserved, 365);
  assert.equal(feedbackRollbackRepair.green.stagingUsersMigratableWithoutInference, 365);
  assert.equal(feedbackRollbackRepair.green.stagingUsersWithLegacyActiveRatings, 0);
  assert.equal(feedbackRollbackRepair.green.externalLlmCalls, 0);
  assert.equal(feedbackRollbackRepair.green.productionChanges, 0);
  assert.equal(feedbackRollbackRepair.nextRequired.id, "B6-PERSONALIZATION-UTILITY-EVIDENCE");
  assert.ok(b.requirements.some((x) => x.id === "NH67-FEEDBACK-ROLLBACK-INTEGRITY" && x.state === "local_code_qa_pass_with_limits"));
  const utilityEvidence = b.localEditorialEdition.personalizationUtilityEvidenceReceipt;
  assert.equal(utilityEvidence.stableId, b.personalizationUtilityEvidenceId);
  assert.equal(utilityEvidence.contract.stableId, b.editorialPersonalizationUtilityContractId);
  assert.equal(utilityEvidence.contract.version, 1);
  assert.equal(utilityEvidence.state, "local_offline_proxy_pass_with_limits");
  assert.equal(utilityEvidence.replay.editionId, "2026-08-11-evening-business.humor.news.tech");
  assert.equal(utilityEvidence.replay.issueCount, 28);
  assert.equal(utilityEvidence.replay.topK, 10);
  assert.equal(utilityEvidence.replay.affinity.baselineDiscounted, 3.265);
  assert.equal(utilityEvidence.replay.affinity.projectedDiscounted, 3.2949);
  assert.equal(utilityEvidence.replay.affinity.discountedGain, 0.0298);
  assert.equal(utilityEvidence.replay.categorySelection.unselectedIssueCount, 0);
  assert.equal(utilityEvidence.replay.sourceDiversity.baselineDistinctCount, 10);
  assert.equal(utilityEvidence.replay.sourceDiversity.projectedDistinctCount, 10);
  assert.equal(utilityEvidence.replay.categoryConcentration.projectedDistinctCount, 4);
  assert.equal(utilityEvidence.counterexample.sourceDistinctBefore, 6);
  assert.equal(utilityEvidence.counterexample.sourceDistinctCandidate, 5);
  assert.equal(utilityEvidence.counterexample.servedCanonicalFallback, true);
  assert.equal(utilityEvidence.green.focusedRegression, "5/5 PASS");
  assert.equal(utilityEvidence.green.fullRegression, "1127/1127 PASS");
  assert.equal(utilityEvidence.green.externalLlmCalls, 0);
  assert.equal(utilityEvidence.nextRequired.id, "B6-HUMAN-BLIND-EDITORIAL-PILOT");
  assert.match(utilityEvidence.boundary, /실제 사용자 만족도/);
  assert.ok(b.requirements.some((x) => x.id === "NH68-PERSONALIZATION-UTILITY-EVIDENCE" && x.state === "local_offline_proxy_pass_with_limits"));
  const humanPilot = b.localEditorialEdition.humanBlindEditorialPilotReadyReceipt;
  assert.equal(humanPilot.state, "historical_receipt_not_runtime_restored");
  assert.equal(humanPilot.runtimeRestored, false);
  assert.equal(humanPilot.currentRuntimePacket, null);
  assert.equal(humanPilot.stableId, b.humanBlindEditorialPilotReadyId);
  assert.equal(humanPilot.inventoryRenewal.currentSnapshotVersion, "v21");
  assert.equal(humanPilot.inventoryRenewal.compatibility.pass, true);
  assert.equal(humanPilot.inventoryRenewal.compatibility.actual.qualityVersion, 13);
  assert.equal(humanPilot.machinePacket.packetId, "BRP-1etcf4c");
  assert.equal(humanPilot.machinePacket.status, "historical_receipt_only");
  assert.equal(humanPilot.machinePacket.issueCount, 42);
  assert.equal(humanPilot.machinePacket.readerIssuePass, 42);
  assert.equal(humanPilot.machinePacket.machineHold, 0);
  assert.equal(humanPilot.machinePacket.englishOnlyLeadCount, 0);
  assert.equal(humanPilot.humanReview.completedRows, 0);
  assert.equal(humanPilot.humanReview.totalRequiredJudgments, 84);
  assert.equal(humanPilot.humanReview.comparisonReady, false);
  assert.equal(humanPilot.supplyBoundary.defaultTodayHttpStatus, 409);
  assert.deepEqual(humanPilot.supplyBoundary.defaultUnderfilledCategoryIds, ["humor"]);
  assert.equal(humanPilot.verification.fullRegression, "1131/1131 PASS");
  assert.equal(humanPilot.nextRequired.id, "B6-HUMAN-BLIND-EDITORIAL-PILOT");
  assert.ok(b.requirements.some((x) => x.id === "NH69-HUMAN-BLIND-EDITORIAL-PILOT-READY" && x.state === "historical_receipt_not_runtime_restored"));
  const semanticReceipt = b.localEditorialEdition.semanticQualityQaReceipt;
  assert.equal(semanticReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(semanticReceipt.rules.exactDuplicateTitleKeepsCoherentLead, true);
  assert.equal(semanticReceipt.rules.selectedCategoryOwnsEditorialValueLens, true);
  assert.deepEqual(semanticReceipt.tests.fullRegression, { total: 1062, passed: 1062, failed: 0 });
  assert.match(semanticReceipt.boundary, /실제 12·19시 판/);
  assert.ok(b.requirements.some((x) => x.id === "NH39-EDITORIAL-SEMANTIC-QUALITY"));
  const diversityReceipt = b.localEditorialEdition.eventDiversityQaReceipt;
  assert.equal(diversityReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(diversityReceipt.rules.selectionOnlyNearDuplicateSuppression, true);
  assert.equal(diversityReceipt.rules.paragraphClusterRuleUnchanged, true);
  assert.equal(diversityReceipt.rules.englishStopWordsExcluded, true);
  assert.equal(diversityReceipt.rules.categoryAndCollectionMetadataExcluded, true);
  assert.equal(diversityReceipt.rules.sportsSubtopicLens, true);
  assert.equal(diversityReceipt.audit.uniqueLeadTitleCount, 91);
  assert.equal(diversityReceipt.audit.nearDuplicatePairCount, 4);
  assert.equal(diversityReceipt.audit.humanBlindReviewCompleted, false);
  assert.deepEqual(diversityReceipt.tests.fullRegression, { total: 1062, passed: 1062, failed: 0 });
  assert.match(diversityReceipt.boundary, /제품 목표·고정 표본·품질 PASS 기준이 아니다/);
  assert.ok(b.requirements.some((x) => x.id === "NH40-EDITORIAL-EVENT-DIVERSITY"));
  const categoryFitReceipt = b.localEditorialEdition.categoryFitQaReceipt;
  assert.equal(categoryFitReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(categoryFitReceipt.rules.categoryGuardSharedByClassifierAndMachineGate, true);
  assert.equal(categoryFitReceipt.simulation.actualElapsedProof, false);
  assert.equal(categoryFitReceipt.simulation.fulfilledCategoryCount, 14);
  assert.equal(categoryFitReceipt.simulation.issueCount, 42);
  assert.equal(categoryFitReceipt.simulation.guardedBadSelectedCount, 0);
  assert.equal(categoryFitReceipt.simulation.improvedHeadlineCount, 7);
  assert.equal(categoryFitReceipt.simulation.llmCalls, 0);
  assert.deepEqual(categoryFitReceipt.tests.focusedRegression, { total: 97, passed: 97, failed: 0 });
  assert.deepEqual(categoryFitReceipt.tests.fullRegression, { total: 1064, passed: 1064, failed: 0 });
  assert.match(categoryFitReceipt.boundary, /실제 12시 시스템 시계 판/);
  assert.ok(b.requirements.some((x) => x.id === "NH41-EDITORIAL-CATEGORY-FIT"));
  const slotCaptureReceipt = b.localEditorialEdition.slotCaptureIntegrityQaReceipt;
  assert.equal(slotCaptureReceipt.rules.defaultSegmentFirst, true);
  assert.equal(slotCaptureReceipt.rules.chronologicalPrerequisitesWithinSegment, true);
  assert.equal(slotCaptureReceipt.rules.evidenceUsesInventoryCompletionTime, true);
  assert.deepEqual(slotCaptureReceipt.tests.focusedRegression, { total: 21, passed: 21, failed: 0 });
  assert.deepEqual(slotCaptureReceipt.tests.fullRegression, { total: 1065, passed: 1065, failed: 0 });
  assert.ok(b.requirements.some((x) => x.id === "NH42-SLOT-CAPTURE-INTEGRITY"));
  const reliabilityReceipt = b.localEditorialEdition.reliabilityHistoryQaReceipt;
  assert.equal(b.editorialReliabilityHistoryContractId, reliabilityReceipt.contractId);
  assert.equal(reliabilityReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(reliabilityReceipt.rules.systemClockObservationsOnly, true);
  assert.equal(reliabilityReceipt.rules.preMonitoringBackfillsExcluded, true);
  assert.equal(reliabilityReceipt.rules.postMonitoringLateCapturesCounted, true);
  assert.equal(reliabilityReceipt.rules.dueSlotsOnlyForToday, true);
  assert.equal(reliabilityReceipt.rules.wholeMissingDaysVisible, true);
  assert.equal(reliabilityReceipt.rules.reportingWindowIsNotCollectionTarget, true);
  assert.deepEqual(reliabilityReceipt.tests.focusedRegression, { total: 25, passed: 25, failed: 0 });
  assert.deepEqual(reliabilityReceipt.tests.fullRegression, { total: 1069, passed: 1069, failed: 0 });
  assert.match(reliabilityReceipt.boundary, /다일 안정성/);
  assert.ok(b.requirements.some((x) => x.id === "NH43-EDITORIAL-RELIABILITY-HISTORY"));
  const qualityHistoryReceipt = b.localEditorialEdition.editorialQualityHistoryQaReceipt;
  assert.equal(b.editorialQualityHistoryContractId, qualityHistoryReceipt.contractId);
  assert.equal(b.editorialQualityHistoryContract.stableId, qualityHistoryReceipt.contractId);
  assert.equal(qualityHistoryReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(qualityHistoryReceipt.rules.immutableSavedEditions, true);
  assert.equal(qualityHistoryReceipt.rules.legacyLineageUnavailableSeparatedFromHashFailure, true);
  assert.equal(qualityHistoryReceipt.rules.humanReviewProgressSeparate, true);
  assert.equal(qualityHistoryReceipt.rules.widestSharedSegmentFrozenPerDueSlot, true);
  assert.equal(qualityHistoryReceipt.rules.automaticFreezeDoesNotActivatePacket, true);
  assert.equal(qualityHistoryReceipt.rules.reportingWindowIsNotCollectionTarget, true);
  assert.deepEqual(qualityHistoryReceipt.tests.focusedRegression, { total: 19, passed: 19, failed: 0 });
  assert.deepEqual(qualityHistoryReceipt.tests.fullRegression, { total: 1077, passed: 1077, failed: 0 });
  assert.match(qualityHistoryReceipt.boundary, /사람 품질 PASS/);
  assert.ok(b.requirements.some((x) => x.id === "NH50-EDITORIAL-QUALITY-HISTORY"));
  const preflightReceipt = b.localEditorialEdition.replayFulfillmentPreflightQaReceipt;
  assert.equal(preflightReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(preflightReceipt.rules.projectedOnly, true);
  assert.equal(preflightReceipt.rules.noEditionPersistence, true);
  assert.equal(preflightReceipt.rules.perCategoryFulfillmentBeforeTotalCount, true);
  assert.equal(preflightReceipt.simulation.actualElapsedTimeProof, false);
  assert.equal(preflightReceipt.simulation.selectedIssueCount, 42);
  assert.equal(preflightReceipt.simulation.metCategoryCount, 14);
  assert.equal(preflightReceipt.simulation.unpromotableRepresentativeCount, 0);
  assert.deepEqual(preflightReceipt.tests.focusedRegression, { total: 31, passed: 31, failed: 0 });
  assert.deepEqual(preflightReceipt.tests.fullRegression, { total: 1069, passed: 1069, failed: 0 });
  assert.match(preflightReceipt.boundary, /실제 12시 정시 저장/);
  assert.ok(b.requirements.some((x) => x.id === "NH44-REPLAY-FULFILLMENT-PREFLIGHT"));
  const semanticLeakReceipt = b.localEditorialEdition.categorySemanticLeakQaReceipt;
  assert.equal(semanticLeakReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(semanticLeakReceipt.rules.incidentContextOverridesObjectKeyword, true);
  assert.equal(semanticLeakReceipt.rules.cultureEventCannotPassTechWithoutTechSubject, true);
  assert.equal(semanticLeakReceipt.simulation.actualElapsedTimeProof, false);
  assert.equal(semanticLeakReceipt.simulation.observedLeakCountBefore, 3);
  assert.equal(semanticLeakReceipt.simulation.selectedLeakCountAfter, 0);
  assert.equal(semanticLeakReceipt.simulation.metCategoryCount, 14);
  assert.equal(semanticLeakReceipt.simulation.selectedIssueCount, 42);
  assert.deepEqual(semanticLeakReceipt.tests.focusedRegression, { total: 142, passed: 142, failed: 0 });
  assert.deepEqual(semanticLeakReceipt.tests.fullRegression, { total: 1069, passed: 1069, failed: 0 });
  assert.match(semanticLeakReceipt.boundary, /실제 12시 정시 저장/);
  assert.ok(b.requirements.some((x) => x.id === "NH45-CATEGORY-SEMANTIC-LEAK-GUARD"));
  const actualLunchReceipt = b.localEditorialEdition.actualLunchSemanticQaReceipt;
  assert.equal(actualLunchReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(actualLunchReceipt.rules.actualElapsedSlot, true);
  assert.equal(actualLunchReceipt.rules.fullDayProof, false);
  assert.equal(actualLunchReceipt.rules.historicalEditionImmutable, true);
  assert.equal(actualLunchReceipt.capture.clockSource, "system");
  assert.equal(actualLunchReceipt.capture.storedSegmentCount, 5);
  assert.equal(actualLunchReceipt.capture.publishableSegmentCount, 5);
  assert.equal(actualLunchReceipt.allCategorySegment.metCategoryCount, 14);
  assert.equal(actualLunchReceipt.allCategorySegment.issueCount, 42);
  assert.equal(actualLunchReceipt.defaultSegment.contentChanged, true);
  assert.notEqual(actualLunchReceipt.defaultSegment.morningFingerprint, actualLunchReceipt.defaultSegment.lunchFingerprint);
  assert.equal(actualLunchReceipt.audit.targeted040LeaksRemaining, 0);
  assert.equal(actualLunchReceipt.audit.observedProblemCount, 6);
  assert.equal(actualLunchReceipt.rules.humanReviewCompleted, false);
  assert.deepEqual(actualLunchReceipt.tests.focusedRegression, { total: 98, passed: 98, failed: 0 });
  assert.deepEqual(actualLunchReceipt.tests.fullRegression, { total: 1070, passed: 1070, failed: 0 });
  assert.match(actualLunchReceipt.boundary, /사람 품질은 HOLD/);
  assert.ok(b.requirements.some((x) => x.id === "NH46-ACTUAL-LUNCH-SEMANTIC-AUDIT"));
  const fullLunchAuditReceipt = b.localEditorialEdition.actualLunchFullAuditQaReceipt;
  assert.equal(fullLunchAuditReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(fullLunchAuditReceipt.rules.auditedObservedEditionSizeIsNotTarget, true);
  assert.equal(fullLunchAuditReceipt.rules.everyStoredIssueAudited, true);
  assert.equal(fullLunchAuditReceipt.rules.historicalEditionImmutable, true);
  assert.equal(fullLunchAuditReceipt.rules.futureEditionsOnly, true);
  assert.equal(fullLunchAuditReceipt.rules.humanReviewCompleted, false);
  assert.equal(fullLunchAuditReceipt.audit.auditedIssueCount, 42);
  assert.equal(fullLunchAuditReceipt.audit.priorKnownAffectedIssueCount, 6);
  assert.equal(fullLunchAuditReceipt.audit.additionalDefectFieldCount, 18);
  assert.equal(fullLunchAuditReceipt.audit.additionalAffectedIssueCount, 17);
  assert.equal(fullLunchAuditReceipt.audit.totalAffectedIssueCount, 23);
  assert.equal(fullLunchAuditReceipt.audit.particleErrorCount, 12);
  assert.equal(fullLunchAuditReceipt.audit.actualEditionHumanQualityPass, false);
  assert.equal(fullLunchAuditReceipt.futureRuleProjection.fixedIssueTarget, false);
  assert.equal(fullLunchAuditReceipt.futureRuleProjection.currentPreviewSelectedCategoryCount, 14);
  assert.equal(fullLunchAuditReceipt.futureRuleProjection.currentPreviewMetCategoryCount, 14);
  assert.equal(fullLunchAuditReceipt.futureRuleProjection.currentPreviewIssueCount, 42);
  assert.equal(fullLunchAuditReceipt.futureRuleProjection.currentPreviewObservedNotTarget, true);
  assert.equal(fullLunchAuditReceipt.futureRuleProjection.actualEveningObserved, false);
  assert.deepEqual(fullLunchAuditReceipt.tests.focusedRegression, { total: 106, passed: 106, failed: 0 });
  assert.deepEqual(fullLunchAuditReceipt.tests.fullRegression, { total: 1070, passed: 1070, failed: 0 });
  assert.match(fullLunchAuditReceipt.boundary, /나머지 19건의 사람 품질 PASS를 뜻하지 않는다/);
  assert.match(fullLunchAuditReceipt.boundary, /실제 19시 판/);
  assert.ok(b.requirements.some((x) => x.id === "NH47-ACTUAL-LUNCH-FULL-AUDIT"));
  const projectedPreflightReceipt = b.localEditorialEdition.projectedEditionPreflightQaReceipt;
  assert.equal(projectedPreflightReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(projectedPreflightReceipt.rules.projectedOnly, true);
  assert.equal(projectedPreflightReceipt.rules.persisted, false);
  assert.equal(projectedPreflightReceipt.rules.actualElapsedProof, false);
  assert.equal(projectedPreflightReceipt.rules.humanInputAllowed, false);
  assert.equal(projectedPreflightReceipt.runtime.issueCount, 42);
  assert.equal(projectedPreflightReceipt.runtime.observedIssueCountIsNotTarget, true);
  assert.equal(projectedPreflightReceipt.runtime.metCategoryCount, 11);
  assert.deepEqual(projectedPreflightReceipt.runtime.missingCategoryIds, ["fashion"]);
  assert.deepEqual(projectedPreflightReceipt.runtime.underfilledCategoryIds, ["science", "art"]);
  assert.equal(projectedPreflightReceipt.runtime.enumeratedTargetedDefectsRemaining, 0);
  assert.deepEqual(projectedPreflightReceipt.tests.focusedRegression, { total: 174, passed: 174, failed: 0 });
  assert.deepEqual(projectedPreflightReceipt.tests.fullRegression, { total: 1070, passed: 1070, failed: 0 });
  assert.match(projectedPreflightReceipt.boundary, /42행은 관측 크기일 뿐 목표가 아니며/);
  assert.match(projectedPreflightReceipt.boundary, /실제 19시 수집/);
  assert.ok(b.requirements.some((x) => x.id === "NH48-PROJECTED-EDITION-PREFLIGHT"));
  const projectedReauditReceipt = b.localEditorialEdition.projectedQualityReauditQaReceipt;
  assert.equal(projectedReauditReceipt.rules.fixedRuntimeCandidateCount, false);
  assert.equal(projectedReauditReceipt.rules.replacementRowsRequireReaudit, true);
  assert.equal(projectedReauditReceipt.rules.sensitiveAllegationRequiresReportedSource, true);
  assert.equal(projectedReauditReceipt.runtime.issueCount, 42);
  assert.equal(projectedReauditReceipt.runtime.observedIssueCountIsNotTarget, true);
  assert.equal(projectedReauditReceipt.runtime.metCategoryCount, 10);
  assert.deepEqual(projectedReauditReceipt.runtime.missingCategoryIds, ["fashion"]);
  assert.deepEqual(projectedReauditReceipt.runtime.underfilledCategoryIds, ["auto", "science", "art"]);
  assert.equal(projectedReauditReceipt.runtime.enumeratedTargetedDefectsRemaining, 0);
  assert.equal(projectedReauditReceipt.runtime.fulfillmentReducedByQualityHold, true);
  assert.deepEqual(projectedReauditReceipt.tests.focusedRegression, { total: 100, passed: 100, failed: 0 });
  assert.deepEqual(projectedReauditReceipt.tests.fullRegression, { total: 1072, passed: 1072, failed: 0 });
  assert.match(projectedReauditReceipt.boundary, /다음 유효 후보가 빈자리를 채운 결과/);
  assert.match(projectedReauditReceipt.boundary, /11\/14에서 10\/14로 낮아졌다/);
  assert.ok(b.requirements.some((x) => x.id === "NH49-DYNAMIC-REPLACEMENT-REAUDIT"));
  const integrityReceipt = b.localEditorialEdition.personalizationIntegrityReceipt;
  assert.equal(integrityReceipt.runtime.liveReplayObserved, true);
  assert.equal(integrityReceipt.runtime.contaminationCount, 0);
  assert.equal(integrityReceipt.runtime.nonSelectedCategoryCount, 0);
  assert.equal(integrityReceipt.runtime.fulfillmentState, "fulfillment_partial");
  assert.deepEqual(integrityReceipt.runtime.missingCategoryIds, ["politics"]);
  assert.equal(integrityReceipt.runtime.issuesWithSourceEvidence, integrityReceipt.runtime.issueCount);
  assert.equal(integrityReceipt.visual.horizontalOverflow, false);
  assert.equal(integrityReceipt.visual.pageErrors, 0);
  assert.ok(integrityReceipt.limits.some((limit) => /사람 A\/B 검수/.test(limit)));
  assert.ok(integrityReceipt.limits.some((limit) => /운영 배포/.test(limit)));
  assert.equal(b.status.deploymentAllowed, false);
  assert.equal(b.adversarialReview.state, "hold");
});

test("product blueprint: explicit taste owns a dynamic three-edition briefing", () => {
  const b = PRODUCT_BLUEPRINT;
  assert.equal(b.editionPolicy.countPerDay, 3);
  assert.deepEqual(b.editionPolicy.editions.map((x) => x.id), ["morning", "midday", "evening"]);
  assert.equal(b.personalizationPolicy.selectedCategoriesOwnNormalFeed, true);
  assert.equal(b.personalizationPolicy.automaticUnselectedMixShare, 0);
  assert.equal(b.personalizationPolicy.globalMustKnowSeparate, true);
  assert.equal(b.personalizationPolicy.dynamicLengthBySelectionAndSupply, true);
  assert.equal(b.personalizationPolicy.fixedItemLimit, false);
  assert.equal(b.personalizationPolicy.qualityFillerAllowed, false);
  assert.equal(b.personalizationPolicy.behaviorCanSilentlyAddCategory, false);
  assert.match(b.tagline, /찾아다니지 마/);
});

test("product blueprint: selection engine separates evidence, LLM editing and verification", () => {
  const e = PRODUCT_BLUEPRINT.selectionEngine;
  assert.equal(e.stableId, PRODUCT_BLUEPRINT.selectionEditorialId);
  assert.deepEqual(e.scoreAxes.map((x) => x.id), ["heat", "importance", "trust", "personalFit", "change"]);
  assert.ok(e.stages.some((x) => /LLM/.test(x.title)));
  assert.ok(e.stages.some((x) => x.title === "검증"));
  assert.ok(e.lanes.some((x) => x.id === "globalMustKnow"));
  assert.ok(e.sourceTrustFields.includes("ownershipGroup"));
  assert.ok(e.sourceTrustFields.includes("syndicationGroup"));
  assert.ok(e.llmRoles.some((x) => x.id === "verifier"));
  assert.ok(e.llmProhibitions.some((x) => /전체 브리핑 재생성/.test(x)));
  assert.ok(e.qualityGates.some((x) => x.id === "criticalMissRate"));
  assert.ok(e.costControls.some((x) => /evidenceHash/.test(x)));
});

test("product blueprint: human docs and admin projection point at the same canon", () => {
  const b = PRODUCT_BLUEPRINT;
  const charter = read("docs/00_NOWHOT_PRODUCT_CHARTER.md");
  const blueprint = read("docs/01_NOWHOT_SYSTEM_BLUEPRINT.md");
  const selection = read("docs/02_NOWHOT_SELECTION_EDITORIAL_ENGINE.md");
  const status = read("docs/NOWHOT_DEVELOPMENT_STATUS.md");
  const benchmark = read("docs/NOWHOT_PRODUCT_BLUEPRINT_002.md");
  const reviewProtocol = read("docs/03_NOWHOT_ADVERSARIAL_REVIEW_PROTOCOL.md");
  const reviewResult = read("docs/04_NOWHOT_ADVERSARIAL_REVIEW_RESULT.md");
  const marketPolicy = read("docs/05_NOWHOT_MARKET_POLICY_BEACHHEAD.md");
  const sourceAudit = read("docs/06_NOWHOT_MARKET_POLICY_SOURCE_AUDIT.md");
  const categoryArchitecture = read("docs/07_NOWHOT_CATEGORY_ARCHITECTURE.md");
  const sourceSample = read("docs/08_NOWHOT_MARKET_POLICY_SOURCE_SAMPLE.md");
  const localEditorial = read("docs/09_NOWHOT_LOCAL_EDITORIAL_EDITION.md");
  const editorialQuality = read("docs/10_NOWHOT_EDITORIAL_QUALITY_GATE.md");
  const editionChange = read("docs/11_NOWHOT_EDITION_CHANGE_AND_REVIEW.md");
  const editorialInventory = read("docs/12_NOWHOT_EDITORIAL_INVENTORY.md");
  const elapsedEvidence = read("docs/13_NOWHOT_ELAPSED_EVIDENCE_AND_HUMAN_REVIEW.md");
  const editorialLineage = read("docs/14_NOWHOT_EDITORIAL_LINEAGE_AND_LLM_RUNTIME.md");
  const personalizationIntegrity = read("docs/15_NOWHOT_PERSONALIZATION_INTEGRITY.md");
  const editorialReviewDesk = read("docs/16_NOWHOT_EDITORIAL_REVIEW_DESK.md");
  const readerQualityFeedback = read("docs/17_NOWHOT_READER_QUALITY_FEEDBACK.md");
  const unservedQualityCarryover = read("docs/18_NOWHOT_UNSERVED_QUALITY_CARRYOVER.md");
  const purposeAlignmentReview = read("docs/19_NOWHOT_PURPOSE_ALIGNMENT_ADVERSARIAL_REVIEW.md");
  const readerPayloadFreeze = read("docs/20_NOWHOT_READER_PAYLOAD_FREEZE_AND_GATE.md");
  const readerEventFrame = read("docs/21_NOWHOT_READER_EVENT_FRAME_COPY.md");
  const independentAudit = read("docs/22_NOWHOT_INDEPENDENT_ADVERSARIAL_AUDIT.md");
  const counterexampleRepair = read("docs/23_NOWHOT_COUNTEREXAMPLE_REPAIR.md");
  const independentReaudit = read("docs/24_NOWHOT_INDEPENDENT_REAUDIT.md");
  const serveableEditionGate = read("docs/25_NOWHOT_SERVEABLE_EDITION_GATE.md");
  const readerLineageGrounding = read("docs/26_NOWHOT_READER_LINEAGE_GROUNDING_GATE.md");
  const eventContinuityFrameGate = read("docs/27_NOWHOT_EVENT_CONTINUITY_FRAME_GATE.md");
  const categoryUniqueFulfillmentGate = read("docs/28_NOWHOT_CATEGORY_UNIQUE_FULFILLMENT_GATE.md");
  const feedbackRollbackGate = read("docs/29_NOWHOT_FEEDBACK_ROLLBACK_GATE.md");
  const personalizationUtilityEvidence = read("docs/30_NOWHOT_PERSONALIZATION_UTILITY_EVIDENCE.md");
  const humanBlindEditorialPilotReady = read("docs/31_NOWHOT_HUMAN_BLIND_EDITORIAL_PILOT_READY.md");
  const admin = read("src/feed/public/admin.html");
  const today = read("src/feed/public/today.html");
  const reviewDeskPage = read("src/feed/public/editorial-desk.html");

  assert.ok(charter.includes(`# ${b.charterId}`));
  assert.ok(prose(charter).includes(b.mission), "machine mission must match the wrapped Markdown charter");
  assert.ok(blueprint.includes(`# ${b.stableId}`));
  assert.ok(selection.includes(`# ${b.selectionEditorialId}`));
  assert.ok(reviewProtocol.includes(b.adversarialReviewId));
  assert.ok(reviewResult.includes(`# ${b.adversarialReviewId}`));
  assert.match(reviewResult, /독립 검수 6개, 재사용 보충 렌즈 1개/);
  assert.match(reviewResult, /비소속 고지/);
  assert.ok(marketPolicy.includes(`# ${b.marketPolicyBeachheadId}`));
  assert.match(marketPolicy, /정치 뉴스는 많이 다뤄졌다는 이유만으로 넣지 않는다/);
  assert.ok(sourceAudit.includes(`# ${b.marketPolicySourceAuditId}`));
  assert.ok(sourceAudit.includes("DEVCHG-NOWHOT-20260810-011"));
  assert.match(sourceAudit, /시장·정책 관련 합계 \| 23/);
  assert.ok(categoryArchitecture.includes(`# ${b.categoryArchitectureId}`));
  assert.ok(categoryArchitecture.includes("DEVCHG-NOWHOT-20260810-008"));
  assert.match(categoryArchitecture, /경제 전문 서비스가 아니다/);
  assert.ok(sourceSample.includes(`# ${b.marketPolicySourceSampleId}`));
  assert.ok(sourceSample.includes("DEVCHG-NOWHOT-20260810-011"));
  assert.match(sourceSample, /3건 일치, 2건 부분 일치/);
  assert.ok(localEditorial.includes(`# ${b.localEditorialEditionId}`));
  assert.ok(localEditorial.includes(b.editionCandidateContractId));
  assert.ok(localEditorial.includes(b.editorialQualityContractId));
  assert.ok(localEditorial.includes("DEVCHG-NOWHOT-20260810-013"));
  assert.ok(editorialQuality.includes(`# ${b.editorialQualityContractId}`));
  assert.ok(editorialQuality.includes(b.blindReviewPacketId));
  assert.ok(editorialQuality.includes("DEVCHG-NOWHOT-20260810-012"));
  assert.ok(editionChange.includes(`# ${b.editionChangeContractId}`));
  assert.ok(editionChange.includes("DEVCHG-NOWHOT-20260810-013"));
  assert.ok(editorialInventory.includes(`# ${b.editorialInventoryContractId}`));
  assert.ok(elapsedEvidence.includes(`# ${b.elapsedEditionEvidenceContractId}`));
  assert.ok(elapsedEvidence.includes("DEVCHG-NOWHOT-20260811-015"));
  assert.ok(editorialLineage.includes(`# ${b.editorialLineageContractId}`));
  assert.ok(editorialLineage.includes(b.editorialLlmContractId));
  assert.ok(editorialLineage.includes(b.editorialLlmCanaryContractId));
  assert.ok(editorialLineage.includes("DEVCHG-NOWHOT-20260811-016"));
  assert.ok(editorialLineage.includes("DEVCHG-NOWHOT-20260811-048"));
  assert.ok(personalizationIntegrity.includes(`# ${b.editorialFulfillmentContractId}`));
  assert.ok(personalizationIntegrity.includes("DEVCHG-NOWHOT-20260811-017"));
  assert.ok(editorialReviewDesk.includes(`# ${b.editorialReviewDeskContractId}`));
  assert.ok(editorialReviewDesk.includes("DEVCHG-NOWHOT-20260811-048"));
  assert.match(editorialReviewDesk, /현재 좌석 외 답과 기계 판정/);
  assert.ok(readerQualityFeedback.includes("DEVCHG-NOWHOT-20260811-049"));
  assert.ok(readerQualityFeedback.includes("NH55-READER-QUALITY-FEEDBACK"));
  assert.ok(unservedQualityCarryover.includes("DEVCHG-NOWHOT-20260811-050"));
  assert.ok(unservedQualityCarryover.includes("NH56-UNSERVED-QUALITY-CARRYOVER"));
  assert.ok(purposeAlignmentReview.includes(`# ${b.purposeAlignmentReviewId}`));
  assert.ok(purposeAlignmentReview.includes(b.localEditorialEdition.purposeAlignmentAdversarialReviewReceipt.changeId));
  assert.match(purposeAlignmentReview, /5\/5 HOLD/);
  assert.match(purposeAlignmentReview, /실제 Techmeme, Ground News, Particle, 뉴닉, 네이버 임직원이 참여한 것이/);
  assert.ok(readerPayloadFreeze.includes(`# ${b.localEditorialEdition.readerPayloadFreezeQaReceipt.stableId}`));
  assert.ok(readerPayloadFreeze.includes(b.localEditorialEdition.readerPayloadFreezeQaReceipt.changeId));
  assert.match(readerPayloadFreeze, /42\/42/);
  assert.match(readerPayloadFreeze, /reader_copy_hold/);
  assert.ok(readerEventFrame.includes(`# ${b.localEditorialEdition.readerEventFrameQaReceipt.stableId}`));
  assert.ok(readerEventFrame.includes(b.localEditorialEdition.readerEventFrameQaReceipt.changeId));
  assert.match(readerEventFrame, /실제 임직원이 참여한 검수가 아니다/);
  assert.ok(independentAudit.includes(`# ${b.independentAdversarialAuditId}`));
  assert.ok(independentAudit.includes(b.localEditorialEdition.independentAdversarialAuditReceipt.changeId));
  assert.match(independentAudit, /BLOCK 1/);
  assert.match(independentAudit, /실제 Techmeme, Ground News, Particle, 뉴닉, 네이버 임직원이나/);
  assert.ok(counterexampleRepair.includes(`# ${b.counterexampleRepairId}`));
  assert.ok(counterexampleRepair.includes(b.localEditorialEdition.counterexampleRepairReceipt.changeId));
  assert.match(counterexampleRepair, /4\/4/);
  assert.ok(independentReaudit.includes(`# ${b.independentReauditId}`));
  assert.ok(independentReaudit.includes(b.localEditorialEdition.independentReauditReceipt.changeId));
  assert.match(independentReaudit, /BLOCK 2/);
  assert.match(independentReaudit, /실제 Techmeme, Ground News, Particle, 뉴닉, 네이버 임직원이나/);
  assert.ok(serveableEditionGate.includes(`# ${b.serveableEditionRepairId}`));
  assert.ok(serveableEditionGate.includes(b.localEditorialEdition.serveableEditionRepairReceipt.changeId));
  assert.match(serveableEditionGate, /HTTP 409/);
  assert.ok(readerLineageGrounding.includes(`# ${b.readerLineageGroundingRepairId}`));
  assert.ok(readerLineageGrounding.includes(b.localEditorialEdition.readerLineageGroundingRepairReceipt.changeId));
  assert.match(readerLineageGrounding, /7\/7 HOLD/);
  assert.ok(eventContinuityFrameGate.includes(`# ${b.eventContinuityFrameRepairId}`));
  assert.ok(eventContinuityFrameGate.includes(b.localEditorialEdition.eventContinuityFrameRepairReceipt.changeId));
  assert.match(eventContinuityFrameGate, /22\/25 PASS/);
  assert.match(eventContinuityFrameGate, /26\/26 PASS/);
  assert.ok(categoryUniqueFulfillmentGate.includes(`# ${b.categoryUniqueFulfillmentRepairId}`));
  assert.ok(categoryUniqueFulfillmentGate.includes(b.localEditorialEdition.categoryUniqueFulfillmentRepairReceipt.changeId));
  assert.match(categoryUniqueFulfillmentGate, /5\/8 PASS/);
  assert.match(categoryUniqueFulfillmentGate, /1,125\/1,125 PASS/);
  assert.ok(feedbackRollbackGate.includes(`# ${b.feedbackRollbackRepairId}`));
  assert.ok(feedbackRollbackGate.includes(b.localEditorialEdition.feedbackRollbackRepairReceipt.changeId));
  assert.match(feedbackRollbackGate, /좋아요 → 완독 → 평가 해제/);
  assert.match(feedbackRollbackGate, /1,126\/1,126 PASS/);
  assert.ok(personalizationUtilityEvidence.includes(`# ${b.personalizationUtilityEvidenceId}`));
  assert.ok(personalizationUtilityEvidence.includes("DEVCHG-NOWHOT-20260811-062"));
  assert.match(personalizationUtilityEvidence, /3\.2650 → 3\.2949/);
  assert.match(personalizationUtilityEvidence, /실제 사용자 만족도/);
  assert.ok(humanBlindEditorialPilotReady.includes(`# ${b.humanBlindEditorialPilotReadyId}`));
  assert.ok(humanBlindEditorialPilotReady.includes(b.changeId));
  assert.ok(humanBlindEditorialPilotReady.includes("NH69-HUMAN-BLIND-EDITORIAL-PILOT-READY"));
  assert.ok(humanBlindEditorialPilotReady.includes(b.localEditorialEdition.humanBlindEditorialPilotReadyReceipt.machinePacket.packetId));
  assert.match(localEditorial, /새 제품이 아니다/);
  assert.match(selection, /사용자마다 전체 브리핑을 새로 생성하는 것/);
  assert.match(selection, /velocity/);
  assert.ok(status.includes(`# ${b.developmentId}`));
  assert.ok(status.includes(b.changeId));
  assert.match(benchmark, /최종 블루프린트 아님/);
  assert.match(admin, /api\/admin\/product-blueprint/);
  assert.match(admin, /범용 카테고리 구조/);
  assert.match(admin, /첫 검증 카테고리 팩/);
  assert.match(admin, /E1-0B 양질 보도 20건·공식 확인 5건/);
  assert.match(admin, /기존 제품 자체 편집 고도화/);
  assert.match(today, /no_qualified_supply/);
  assert.match(today, /기계 유효 후보 없음/);
  assert.match(admin, /고정 표본 수는 제품 법칙이 아님/);
  assert.match(admin, /핵심 반례 수리 후 독립 재검수/);
  assert.match(admin, /실제 응답 제공 게이트 수리/);
  assert.match(admin, /독자 문장·paragraph 근거 결박/);
  assert.match(admin, /사건 연속성·관련기사 프레임 수리/);
  assert.match(admin, /선택 분야별 고유 사건 충족 수리/);
  assert.match(admin, /중간 신호 뒤 평가 삭제 정확 원복/);
  assert.match(admin, /기본 취향과 명시 평가를 분리/);
  assert.match(admin, /동일 판본 개인화 효용·다양성 가드/);
  assert.match(admin, /실제 만족도는 아직 HOLD/);
  assert.match(admin, /2인 블라인드 편집 파일럿 준비/);
  assert.match(admin, /과거 패킷 영수증 ≠ 현재 검수 가능 상태/);
  assert.match(admin, /적합 최종/);
  assert.match(admin, /실제 판 사건 다양성/);
  assert.match(admin, /현재 목적 적합성 독립 재검수/);
  assert.match(admin, /purposeAlignmentAdversarialReviewReceipt/);
  assert.match(admin, /readerPayloadFreezeQaReceipt/);
  assert.match(admin, /독자 문장 동결 게이트/);
  assert.match(admin, /분야 적합성·제목 완결 모사/);
  assert.match(admin, /실측 분야 의미 누수 재검수/);
  assert.match(admin, /실제 낮 판 42건 전수 필드 감사/);
  assert.match(admin, /현재 지면 안전 상한 · 제품 목표 아님/);
  assert.match(admin, /불변 활성 판 편집 품질검수/);
  assert.match(admin, /검수 패킷 원장/);
  assert.match(admin, /2인 불일치 조정/);
  assert.match(admin, /아침·낮·저녁 판본 변화 영수증/);
  assert.match(admin, /개인판 슬롯 재고/);
  assert.match(admin, /실제 슬롯 실행 영수증/);
  assert.match(admin, /주장 계보·선택형 LLM 영수증/);
  assert.match(admin, /단발 LLM canary/);
  assert.match(admin, /세 슬롯 코드 경로 리플레이/);
  assert.match(admin, /판본 품질 누적 원장/);
  assert.match(admin, /판본 연속성·독자 문체·고정 상단 전환/);
  assert.match(admin, /독자 화면 편집 데스크/);
  assert.match(admin, /\/admin\/editorial-desk/);
  assert.match(admin, /호르무즈 모닝 → 런치: 같은 사건의 후속 보도/);
  assert.match(admin, /슬롯별 자동 검수 패킷/);
  assert.match(admin, /독립 검수 원장/);
  assert.match(admin, /api\/admin\/editorial-review/);
  assert.match(reviewDeskPage, /noindex,nofollow/);
  assert.match(reviewDeskPage, /api\/admin\/editorial-desk/);
  assert.match(reviewDeskPage, /api\/admin\/editorial-review/);
  assert.match(reviewDeskPage, /setTimeout\(flushSave,450\)/);
  assert.doesNotMatch(admin, /claude\.ai\/code\/artifact/);
});
