import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { createRequire } from "node:module";
import { FeedStore } from "../src/feed/store.js";
import { createServer } from "../src/feed/server.js";
import { RELEASES, releaseHistoryHtml } from "../src/feed/release-notes.js";

test("service requests survive restart, dedupe retries, enforce limits and roll back failed writes", (t) => {
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"nh-feedback-"));
  t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const file=path.join(dir,"store.json"), store=new FeedStore({file,clock:()=>"2026-09-05T03:00:00Z"});
  const user=store.createUser();
  const input={kind:"suggestion",message:"날짜 선택을 더 편하게 해주세요.",requestId:randomUUID(),build:"test"};
  const receipt=store.addServiceFeedback(user.id,input);
  assert.equal(store.addServiceFeedback(user.id,input).id,receipt.id);
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,message:"다른 요청 내용입니다."}),{status:409});
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,kind:"admin"}),{status:400});
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,message:"짧음"}),{status:400});
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,message:"a".repeat(2001)}),{status:400});
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,requestId:"invalid"}),{status:400});
  assert.deepEqual(new FeedStore({file}).serviceFeedback,[receipt]);
  const bytes=fs.readFileSync(file,"utf8");
  store.file=path.join(dir,"missing","store.json");
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,requestId:randomUUID()}));
  assert.equal(store.serviceFeedback.length,1);
  assert.equal(fs.readFileSync(file,"utf8"),bytes);
  store.file=file;
  store._coldDirty=true;
  const failedCold=path.join(dir,"store.json.cold.tmp");fs.mkdirSync(failedCold);
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,requestId:randomUUID()}));
  assert.equal(new FeedStore({file}).serviceFeedback.length,1);
  fs.rmdirSync(failedCold);
  for(let i=0;i<4;i++)store.addServiceFeedback(user.id,{...input,requestId:randomUUID()});
  assert.throws(()=>store.addServiceFeedback(user.id,{...input,requestId:randomUUID()}),{status:429});
  assert.equal(store.addServiceFeedback(user.id,input).id,receipt.id,"retry still succeeds at daily limit");
});

test("private feedback API validates origin/owner, persists before receipt and gates admin readback", async(t)=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"nh-feedback-api-")), file=path.join(dir,"store.json");
  const server=createServer({file,adminToken:"feedback-test-admin",sources:[{id:"test",kind:"community",async fetch(){return [];}}]});
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  t.after(()=>{server.closeAllConnections();server.close();fs.rmSync(dir,{recursive:true,force:true});});
  const base=`http://127.0.0.1:${server.address().port}`;
  const post=(route,body,headers={})=>fetch(base+route,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});
  const session=await post("/api/session",{}), {userId}=await session.json();
  const cookie=session.headers.getSetCookie().map(c=>c.split(";")[0]).join("; ");
  const input={userId,kind:"bug",message:"<img src=x onerror=alert(1)> 화면 오류 제보",requestId:randomUUID()};
  assert.equal((await post("/api/feedback",input)).status,403);
  assert.equal((await post("/api/feedback",input,{cookie,origin:"https://foreign.test"})).status,403);
  assert.equal((await post("/api/feedback",input,{cookie,"sec-fetch-site":"cross-site"})).status,403);
  assert.equal((await post("/api/feedback",input,{cookie,"content-type":"text/plain"})).status,415);
  assert.equal((await post("/api/feedback",null,{cookie})).status,400);
  const response=await post("/api/feedback",input,{cookie,origin:base});
  assert.equal(response.status,201);
  const receipt=await response.json();
  assert.deepEqual(Object.keys(receipt).sort(),["createdAt","id","ok"]);
  assert.equal((await (await post("/api/feedback",input,{cookie})).json()).id,receipt.id);
  assert.equal(JSON.parse(fs.readFileSync(file,"utf8")).serviceFeedback[0].id,receipt.id);
  fs.mkdirSync(file+".tmp");
  const failed=await post("/api/feedback",{...input,requestId:randomUUID()},{cookie});
  assert.equal(failed.status,503);assert.ok(!(await failed.text()).includes(dir));
  assert.equal(JSON.parse(fs.readFileSync(file,"utf8")).serviceFeedback.length,1);
  fs.rmdirSync(file+".tmp");
  const other=await post("/api/session",{});
  const otherCookie=other.headers.getSetCookie().map(c=>c.split(";")[0]).join("; ");
  assert.equal((await post("/api/feedback",input,{cookie:otherCookie})).status,403);
  assert.equal((await fetch(base+"/api/admin/feedback")).status,401);
  const admin=await (await fetch(base+"/api/admin/feedback",{headers:{"x-admin-token":"feedback-test-admin"}})).json();
  assert.equal(admin.requests.length,1);assert.equal(admin.requests[0].message,input.message);
  assert.equal((await fetch(base+"/api/feedback")).status,404,"no public request list");
  const html=await (await fetch(base+"/about")).text();
  assert.equal((html.match(/<details class="release"/g)||[]).length,RELEASES.length);
  assert.equal((html.match(/class="release" open/g)||[]).length,1);
  for(const release of RELEASES)assert.ok(html.includes(release.id));
  assert.ok(!html.includes("<!-- NOWHOT_RELEASE_HISTORY -->"));
  RELEASES.push({id:'"<x>',date:"<x>",title:"<script>bad()</script>",items:["<img onerror=bad()>"]});
  try{const safe=releaseHistoryHtml();assert.ok(safe.includes("&lt;script&gt;"));assert.ok(!safe.includes("<script>"));}finally{RELEASES.pop();}

  let chromium;try{({chromium}=createRequire(import.meta.url)("playwright"));}catch{}
  if(!chromium)return;
  const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});
  t.after(()=>browser.close());
  const context=await browser.newContext({viewport:{width:393,height:852},serviceWorkers:"block"});
  await context.route("**/*",route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  const page=await context.newPage();
  const attempts=[];
  await page.route("**/api/feedback",route=>{
    attempts.push(route.request().postDataJSON());
    return attempts.length===1?route.fulfill({status:503,json:{error:"저장하지 못했어요. 다시 보내 주세요."}}):route.continue();
  });
  await page.goto(base+"/feedback");
  await page.locator("#message").fill("[로컬 QA] 관심 분야 선택이 편해졌습니다.");
  await page.locator("#submit").click();
  await page.waitForFunction(()=>document.getElementById("status").textContent.includes("저장하지 못했어요"));
  assert.match(await page.locator("#message").inputValue(),/로컬 QA/);
  await page.locator("#submit").click();
  await page.waitForFunction(()=>document.getElementById("status").textContent.includes("접수되었습니다"));
  assert.equal(attempts[0].requestId,attempts[1].requestId);
  assert.equal(await page.locator("#again").isVisible(),true);
  await page.screenshot({path:"/tmp/nh120-feedback-mobile.png",fullPage:true});
  await page.goto(base+"/admin");
  await page.evaluate(()=>localStorage.setItem("admin_token","feedback-test-admin"));await page.reload();
  await page.getByRole("button",{name:"개선 요청",exact:true}).click();
  await page.waitForFunction(()=>document.getElementById("panel").textContent.includes("화면 오류 제보"));
  assert.equal(await page.locator("#panel img").count(),0,"admin renders submitted markup as text");
  await page.goto(base+"/about#updates");
  assert.equal(await page.locator(".release").count(),RELEASES.length);
  await page.screenshot({path:"/tmp/nh120-history-mobile.png",fullPage:true});
});
